sulu_form.get_lists_fields:
    path: '/form/lists/fields.{_format}'
    methods: GET
    controller: 'sulu_form.list_controller::cgetFieldsAction'
    format: json
    requirements: { _format: json|csv }

sulu_form.get_lists:
    path: '/form/lists.{_format}'
    methods: GET
    controller: 'sulu_form.list_controller::cgetAction'
    format: json
    requirements: { _format: json|csv }

sulu_form.get_forms:
    path: '/forms.{_format}'
    methods: GET
    controller: 'sulu_form.form_controller::cgetAction'
    format: json
    requirements: { _format: json|csv }

sulu_form.get_form:
    path: '/forms/{id}.{_format}'
    methods: GET
    controller: 'sulu_form.form_controller::getAction'
    format: json
    requirements: { _format: json|csv }

sulu_form.post_form:
    path: '/forms.{_format}'
    methods: POST
    controller: 'sulu_form.form_controller::postAction'
    format: json
    requirements: { _format: json|csv }

sulu_form.put_form:
    path: '/forms/{id}.{_format}'
    methods: PUT
    controller: 'sulu_form.form_controller::putAction'
    format: json
    requirements: { _format: json|csv }

sulu_form.delete_form:
    path: '/forms/{id}.{_format}'
    methods: DELETE
    controller: 'sulu_form.form_controller::deleteAction'
    format: json
    requirements: { _format: json|csv }

sulu_form.post_form_trigger:
    path: '/forms/{id}.{_format}'
    methods: POST
    controller: 'sulu_form.form_controller::postTriggerAction'
    format: json
    requirements: { _format: json|csv }

sulu_form.get_dynamics:
    path: '/form/dynamics.{_format}'
    methods: GET
    controller: 'sulu_form.dynamic_controller::cgetAction'
    format: json
    requirements: { _format: json|csv }

sulu_form.delete_dynamic:
    path: '/form/dynamics/{id}.{_format}'
    methods: DELETE
    controller: 'sulu_form.dynamic_controller::deleteAction'
    format: json
    requirements: { _format: json|csv }

sulu_form.get_mail_chimp_values:
    path: /mail_chimp_values
    methods: GET
    controller: 'sulu_form.mailchimp_values_controller::cgetAction'

sulu_form.get_mail_chimp_value:
    path: /mail_chimp_value/{id}
    methods: GET
    controller: 'sulu_form.mailchimp_values_controller::getAction'

sulu_form.get_sendinblue_values:
    path: /sendinblue_values
    methods: GET
    controller: 'sulu_form.controller.brevo_list_select_controller::cgetAction'

sulu_form.get_sendinblue_value:
    path: /sendinblue_values/{id}
    methods: GET
    controller: 'sulu_form.controller.brevo_list_select_controller::getAction'

sulu_form.get_sendinblue_mail_templates:
    path: /sendinblue_mail_templates
    methods: GET
    controller: 'sulu_form.controller.brevo_mail_template_select_controller::cgetAction'

sulu_form.get_sendinblue_mail_template:
    path: /sendinblue_mail_templates/{id}
    methods: GET
    controller: 'sulu_form.controller.brevo_mail_template_select_controller::getAction'
