<?php

/*
 * This file is part of Sulu.
 *
 * (c) MASSIVE ART WebServices GmbH
 *
 * This source file is subject to the MIT license that is bundled
 * with this source code in the file LICENSE.
 */

namespace Sulu\Bundle\FormBundle\Admin;

use Sulu\Bundle\AdminBundle\Navigation\ContentNavigationItem;
use Sulu\Bundle\AdminBundle\Navigation\ContentNavigationProviderInterface;

/**
 * Generated by https://github.com/alexander-schranz/sulu-backend-bundle.
 */
class FormNavigationProvider implements ContentNavigationProviderInterface
{
    /**
     * {@inheritdoc}
     */
    public function getNavigationItems(array $options = [])
    {
        $navigationItems = [];

        $navigationItems['detail'] = new ContentNavigationItem('content-navigation.webspace.general');
        $navigationItems['detail']->setPosition(10);
        $navigationItems['detail']->setAction('general');
        $navigationItems['detail']->setComponent('forms@suluform');
        $navigationItems['detail']->setComponentOptions([
            'display' => 'form',
            'content' => 'general',
        ]);

        return $navigationItems;
    }
}
