<?php

namespace L91\Sulu\Bundle\FormBundle\Admin;

use Sulu\Bundle\AdminBundle\Admin\Admin;
use Sulu\Bundle\AdminBundle\Navigation\Navigation;
use Sulu\Bundle\AdminBundle\Navigation\NavigationItem;
use Sulu\Component\Security\Authorization\SecurityCheckerInterface;

/**
 * Generated by https://github.com/alexander-schranz/sulu-backend-bundle.
 */
class FormAdmin extends Admin
{
    public function __construct(
        SecurityCheckerInterface $securityChecker,
        $title
    ) {
        // set root navigation
        $rootNavigationItem = new NavigationItem($title);

        // parent navigation
        $section = new NavigationItem('navigation.modules');

        // create section
        $navigationItem = new NavigationItem('l91_sulu_form.form');
        $navigationItem->setIcon('magic');
        $section->addChild($navigationItem);

        // add Form navigation
        if ($securityChecker->hasPermission('l91.sulu.form.forms', 'view')) {
            $childItem = new NavigationItem('l91_sulu_form.forms');
            $childItem->setAction('l91/forms');
            $childItem->setPosition(10);
            $navigationItem->addChild($childItem);
        }

        // add section only when exist
        if ($navigationItem->hasChildren()) {
            $rootNavigationItem->addChild($section);
        }

        // set navigation
        $this->setNavigation(new Navigation($rootNavigationItem));
    }

    /**
     * {@inheritdoc}
     */
    public function getCommands()
    {
        return [];
    }

    /**
     * {@inheritdoc}
     */
    public function getJsBundleName()
    {
        return 'l91suluform';
    }

    /**
     * {@inheritDoc}
     */
    public function getSecurityContexts()
    {
        return [
            'Sulu' => [
                'Form' => [
                    'l91.sulu.form.forms',
                ]
            ]
        ];
    }
}
