<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.public_alias.sulu_page.command.workspace_import' shared service.

return $this->services['console.command.public_alias.sulu_page.command.workspace_import'] = new \Sulu\Bundle\PageBundle\Command\WorkspaceImportCommand();
