<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'cache_warmer' shared service.

return $this->services['cache_warmer'] = new \Symfony\Component\HttpKernel\CacheWarmer\CacheWarmerAggregate(new RewindableGenerator(function () {
    yield 0 => ($this->services['sulu_core.list_builder.field_descriptor_factory'] ?? $this->load('getSuluCore_ListBuilder_FieldDescriptorFactoryService.php'));
    yield 1 => ($this->privates['templating.cache_warmer.template_paths'] ?? $this->load('getTemplating_CacheWarmer_TemplatePathsService.php'));
    yield 2 => ($this->services['sulu_form_test.dynamic_form_metadata_loader'] ?? $this->load('getSuluFormTest_DynamicFormMetadataLoaderService.php'));
    yield 3 => ($this->privates['validator.mapping.cache_warmer'] ?? $this->load('getValidator_Mapping_CacheWarmerService.php'));
    yield 4 => ($this->privates['translation.warmer'] ?? $this->load('getTranslation_WarmerService.php'));
    yield 5 => ($this->privates['router.cache_warmer'] ?? $this->load('getRouter_CacheWarmerService.php'));
    yield 6 => ($this->privates['annotations.cache_warmer'] ?? $this->load('getAnnotations_CacheWarmerService.php'));
    yield 7 => ($this->privates['serializer.mapping.cache_warmer'] ?? $this->load('getSerializer_Mapping_CacheWarmerService.php'));
    yield 8 => ($this->privates['twig.cache_warmer'] ?? $this->load('getTwig_CacheWarmerService.php'));
    yield 9 => ($this->privates['twig.template_cache_warmer'] ?? $this->load('getTwig_TemplateCacheWarmerService.php'));
    yield 10 => ($this->privates['sulu.cache.warmer.structure'] ?? $this->load('getSulu_Cache_Warmer_StructureService.php'));
    yield 11 => ($this->privates['doctrine.orm.proxy_cache_warmer'] ?? $this->load('getDoctrine_Orm_ProxyCacheWarmerService.php'));
    yield 12 => ($this->privates['sulu_admin.xml_form_metadata_loader'] ?? $this->load('getSuluAdmin_XmlFormMetadataLoaderService.php'));
    yield 13 => ($this->privates['sulu_admin.structure_form_metadata_loader'] ?? $this->load('getSuluAdmin_StructureFormMetadataLoaderService.php'));
}, 14), true, ($this->targetDirs[0].'/adminAdminTestDebugProjectContainerDeprecations.log'));
