<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'doctrine_cache.providers.sulu_collaboration_entity' shared service.

return $this->services['doctrine_cache.providers.sulu_collaboration_entity'] = new \Doctrine\Common\Cache\FilesystemCache(($this->targetDirs[0].'/sulu/collaboration/entity'), NULL, 2);
