<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doctrine_phpcr.jackalope_doctrine_dbal.schema' shared service.

return $this->privates['doctrine_phpcr.jackalope_doctrine_dbal.schema'] = new \Jackalope\Transport\DoctrineDBAL\RepositorySchema([], ($this->services['doctrine.dbal.default_connection'] ?? $this->getDoctrine_Dbal_DefaultConnectionService()));
