<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'doctrine_phpcr.admin.default_session' shared service.

return $this->services['doctrine_phpcr.admin.default_session'] = ($this->privates['doctrine_phpcr.admin.jackalope.repository.default'] ?? $this->load('getDoctrinePhpcr_Admin_Jackalope_Repository_DefaultService.php'))->login(($this->privates['doctrine_phpcr.admin.default_credentials'] ?? ($this->privates['doctrine_phpcr.admin.default_credentials'] = new \PHPCR\SimpleCredentials($this->getEnv('PHPCR_USERNAME'), $this->getEnv('PHPCR_PASSWORD')))), NULL);
