<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'dtl_content.form.type.home' shared service.

return $this->privates['dtl_content.form.type.home'] = new \Sulu\Bundle\PageBundle\Form\Type\HomeDocumentType();
