<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doctrine_phpcr.admin.jackalope.repository.default' shared service.

return $this->privates['doctrine_phpcr.admin.jackalope.repository.default'] = ($this->privates['doctrine_phpcr.jackalope.repository.factory.service.doctrinedbal'] ?? ($this->privates['doctrine_phpcr.jackalope.repository.factory.service.doctrinedbal'] = new \Jackalope\RepositoryFactoryDoctrineDBAL()))->getRepository(['jackalope.doctrine_dbal_connection' => ($this->services['doctrine.dbal.default_connection'] ?? $this->getDoctrine_Dbal_DefaultConnectionService()), 'jackalope.check_login_on_server' => false]);
