<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'dtl_content.form.type.page' shared service.

return $this->privates['dtl_content.form.type.page'] = new \Sulu\Bundle\PageBundle\Form\Type\PageDocumentType(($this->services['sulu.phpcr.session'] ?? $this->getSulu_Phpcr_SessionService()), ($this->services['sulu_document_manager.document_manager'] ?? $this->getSuluDocumentManager_DocumentManagerService()), ($this->privates['sulu_document_manager.metadata_factory'] ?? $this->getSuluDocumentManager_MetadataFactoryService()));
