<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'dtl_content.form.factory.document_type' shared service.

return $this->privates['dtl_content.form.factory.document_type'] = new \Sulu\Component\Content\Form\Type\DocumentObjectType(($this->services['sulu_document_manager.document_manager'] ?? $this->getSuluDocumentManager_DocumentManagerService()));
