<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'doctrine_phpcr.jackalope_doctrine_dbal.schema_listener' shared service.

return $this->privates['doctrine_phpcr.jackalope_doctrine_dbal.schema_listener'] = new \Doctrine\Bundle\PHPCRBundle\EventListener\JackalopeDoctrineDbalSchemaListener(($this->privates['doctrine_phpcr.jackalope_doctrine_dbal.schema'] ?? $this->load('getDoctrinePhpcr_JackalopeDoctrineDbal_SchemaService.php')));
