<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.security.voter.test_voter' shared service.

return $this->privates['debug.security.voter.test_voter'] = new \Symfony\Component\Security\Core\Authorization\Voter\TraceableVoter(($this->privates['test_voter'] ?? ($this->privates['test_voter'] = new \Sulu\Bundle\TestBundle\Testing\TestVoter())), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));
