<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_rest.routing.loader.reader.controller' shared service.

return $this->privates['fos_rest.routing.loader.reader.controller'] = new \FOS\RestBundle\Routing\Loader\Reader\RestControllerReader(($this->privates['fos_rest.routing.loader.reader.action'] ?? $this->load('getFosRest_Routing_Loader_Reader_ActionService.php')), ($this->privates['annotations.cached_reader'] ?? $this->getAnnotations_CachedReaderService()));
