<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_rest.serializer.exception_normalizer.jms' shared service.

return $this->privates['fos_rest.serializer.exception_normalizer.jms'] = new \Sulu\Component\Rest\ExceptionSerializerHandler(($this->privates['fos_rest.exception.messages_map'] ?? ($this->privates['fos_rest.exception.messages_map'] = new \FOS\RestBundle\Util\ExceptionValueMap([]))), true, 'test');
