<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'fos_rest.view_handler' shared service.

$this->services['fos_rest.view_handler'] = $instance = new \FOS\RestBundle\View\ViewHandler(($this->services['router'] ?? $this->getRouterService()), ($this->privates['fos_rest.serializer.jms'] ?? $this->load('getFosRest_Serializer_JmsService.php')), ($this->services['templating'] ?? $this->load('getTemplatingService.php')), ($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ['json' => false, 'csv' => false, 'html' => true], 400, 204, false, ['html' => 302], 'twig', ['serializeNullStrategy' => true]);

$instance->registerHandler('csv', [0 => ($this->privates['sulu_core.rest.view_handler.csv'] ?? $this->load('getSuluCore_Rest_ViewHandler_CsvService.php')), 1 => 'createResponse']);

return $instance;
