<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'hateoas.expression.link' shared service.

return $this->services['hateoas.expression.link'] = new \Hateoas\Expression\LinkExpressionFunction(($this->services['hateoas.helper.link'] ?? $this->getHateoas_Helper_LinkService()));
