<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'hateoas.event_subscriber.json' shared service.

return $this->services['hateoas.event_subscriber.json'] = new \Hateoas\Serializer\EventSubscriber\JsonEventSubscriber(($this->privates['hateoas.serializer.json_hal'] ?? ($this->privates['hateoas.serializer.json_hal'] = new \Hateoas\Serializer\JsonHalSerializer())), ($this->privates['hateoas.links_factory'] ?? $this->load('getHateoas_LinksFactoryService.php')), ($this->privates['hateoas.embeds_factory'] ?? $this->load('getHateoas_EmbedsFactoryService.php')), ($this->privates['hateoas.inline_deferrer.embeds'] ?? $this->load('getHateoas_InlineDeferrer_EmbedsService.php')), ($this->privates['hateoas.inline_deferrer.links'] ?? $this->load('getHateoas_InlineDeferrer_LinksService.php')));
