<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'hateoas.inline_deferrer.embeds' shared service.

return $this->privates['hateoas.inline_deferrer.embeds'] = new \Hateoas\Serializer\Metadata\InlineDeferrer(($this->privates['jms_serializer.metadata_factory'] ?? $this->getJmsSerializer_MetadataFactoryService()));
