<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'hateoas.serializer.json_hal' shared service.

return $this->privates['hateoas.serializer.json_hal'] = new \Hateoas\Serializer\JsonHalSerializer();
