<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'jms_serializer.metadata.chain_driver' shared service.

return $this->privates['jms_serializer.metadata.chain_driver'] = new \Metadata\Driver\DriverChain([0 => ($this->privates['jms_serializer.metadata.yaml_driver'] ?? $this->load('getJmsSerializer_Metadata_YamlDriverService.php')), 1 => ($this->privates['jms_serializer.metadata.xml_driver'] ?? $this->load('getJmsSerializer_Metadata_XmlDriverService.php')), 2 => ($this->privates['jms_serializer.metadata.php_driver'] ?? $this->load('getJmsSerializer_Metadata_PhpDriverService.php')), 3 => ($this->privates['jms_serializer.metadata.annotation_driver'] ?? $this->load('getJmsSerializer_Metadata_AnnotationDriverService.php'))]);
