<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'jms_serializer.handler_registry' shared service.

return $this->services['jms_serializer.handler_registry'] = new \FOS\RestBundle\Serializer\JMSHandlerRegistry(($this->privates['fos_rest.serializer.jms_handler_registry.inner'] ?? $this->getFosRest_Serializer_JmsHandlerRegistry_InnerService()));
