<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'massive_search.metadata.file_locator' shared service.

return $this->privates['massive_search.metadata.file_locator'] = new \Metadata\Driver\FileLocator(['Sulu\\Bundle\\ContactBundle\\Entity' => '/Users/danielmathis/Development/sulu-website/sulu-docker/project/vendor/sulu/sulu-form-bundle/vendor/sulu/sulu/src/Sulu/Bundle/ContactBundle/Resources/config/massive-search', 'Sulu\\Bundle\\MediaBundle\\Entity' => '/Users/danielmathis/Development/sulu-website/sulu-docker/project/vendor/sulu/sulu-form-bundle/vendor/sulu/sulu/src/Sulu/Bundle/MediaBundle/Resources/config/massive-search', 'Sulu\\Bundle\\CategoryBundle\\Entity' => '/Users/danielmathis/Development/sulu-website/sulu-docker/project/vendor/sulu/sulu-form-bundle/vendor/sulu/sulu/src/Sulu/Bundle/CategoryBundle/Resources/config/massive-search']);
