<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'massive_search.metadata.driver.chain' shared service.

return $this->privates['massive_search.metadata.driver.chain'] = new \Metadata\Driver\DriverChain([0 => ($this->privates['massive_search.metadata.driver.xml'] ?? $this->load('getMassiveSearch_Metadata_Driver_XmlService.php'))]);
