<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'massive_search.adapter.zend_lucene' shared service.

return $this->services['massive_search.adapter.zend_lucene'] = new \Massive\Bundle\SearchBundle\Search\Adapter\ZendLuceneAdapter(($this->privates['sulu_search.search.factory'] ?? ($this->privates['sulu_search.search.factory'] = new \Sulu\Bundle\SearchBundle\Search\Factory())), ($this->targetDirs[3].'/indexes'), ($this->services['filesystem'] ?? ($this->services['filesystem'] = new \Symfony\Component\Filesystem\Filesystem())), false, 'UTF-8');
