<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'massive_search.object_to_document_converter' shared service.

return $this->privates['massive_search.object_to_document_converter'] = new \Massive\Bundle\SearchBundle\Search\ObjectToDocumentConverter(($this->privates['sulu_search.search.factory'] ?? ($this->privates['sulu_search.search.factory'] = new \Sulu\Bundle\SearchBundle\Search\Factory())), ($this->privates['massive_search.metadata.field_evaluator'] ?? $this->load('getMassiveSearch_Metadata_FieldEvaluatorService.php')), ($this->privates['massive_search.converter'] ?? $this->load('getMassiveSearch_ConverterService.php')));
