<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'massive_search.metadata.factory' shared service.

$this->privates['massive_search.metadata.factory'] = $instance = new \Metadata\MetadataFactory(($this->privates['massive_search.metadata.driver.chain'] ?? $this->load('getMassiveSearch_Metadata_Driver_ChainService.php')), 'Metadata\\ClassHierarchyMetadata', true);

$instance->setCache(($this->privates['massive_search.metadata.cache.file_cache'] ?? ($this->privates['massive_search.metadata.cache.file_cache'] = new \Metadata\Cache\FileCache(($this->targetDirs[0].'/massive-search')))));

return $instance;
