<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'massive_search.search_manager' shared service.

return $this->services['massive_search.search_manager'] = new \Massive\Bundle\SearchBundle\Search\SearchManager(($this->services['massive_search.adapter.zend_lucene'] ?? $this->load('getMassiveSearch_Adapter_ZendLuceneService.php')), ($this->privates['massive_search.metadata.provider.chain'] ?? $this->load('getMassiveSearch_Metadata_Provider_ChainService.php')), ($this->privates['massive_search.object_to_document_converter'] ?? $this->load('getMassiveSearch_ObjectToDocumentConverterService.php')), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()), ($this->privates['massive_search.prefix_decorator'] ?? $this->load('getMassiveSearch_PrefixDecoratorService.php')), ($this->privates['massive_search.metadata.field_evaluator'] ?? $this->load('getMassiveSearch_Metadata_FieldEvaluatorService.php')));
