<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'massive_search.command.status' shared service.

$this->privates['massive_search.command.status'] = $instance = new \Massive\Bundle\SearchBundle\Command\StatusCommand(($this->services['massive_search.search_manager'] ?? $this->load('getMassiveSearch_SearchManagerService.php')));

$instance->setName('massive:search:status');

return $instance;
