<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'massive_search.command.reindex' shared service.

$this->privates['massive_search.command.reindex'] = $instance = new \Massive\Bundle\SearchBundle\Command\ReindexCommand(($this->privates['massive_search.reindex.resume_manager'] ?? ($this->privates['massive_search.reindex.resume_manager'] = new \Massive\Bundle\SearchBundle\Search\Reindex\ResumeManager())), ($this->services['massive_search.search_manager'] ?? $this->load('getMassiveSearch_SearchManagerService.php')), ($this->privates['massive_search.reindex.provider_registry'] ?? $this->load('getMassiveSearch_Reindex_ProviderRegistryService.php')), 'test');

$instance->setName('massive:search:reindex');

return $instance;
