<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'massive_search.metadata.provider.chain' shared service.

return $this->privates['massive_search.metadata.provider.chain'] = new \Massive\Bundle\SearchBundle\Search\Metadata\Provider\ChainProvider([0 => ($this->privates['massive_search.metadata.provider.default'] ?? $this->load('getMassiveSearch_Metadata_Provider_DefaultService.php')), 1 => ($this->privates['sulu_page.search.metadata.provider.structure'] ?? $this->load('getSuluPage_Search_Metadata_Provider_StructureService.php'))]);
