<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'massive_search.converter' shared service.

$this->privates['massive_search.converter'] = $instance = new \Massive\Bundle\SearchBundle\Search\Converter\ConverterManager();

$instance->addConverter('date', ($this->privates['massive_search.converter.date_converter'] ?? ($this->privates['massive_search.converter.date_converter'] = new \Massive\Bundle\SearchBundle\Search\Converter\Types\DateConverter())));
$instance->addConverter('json', ($this->privates['massive_search.converter.json_converter'] ?? ($this->privates['massive_search.converter.json_converter'] = new \Massive\Bundle\SearchBundle\Search\Converter\Types\JsonConverter())));
$instance->addConverter('tags', ($this->privates['sulu_tag.search.tags_converter'] ?? $this->load('getSuluTag_Search_TagsConverterService.php')));

return $instance;
