<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'massive_search.command.init' shared service.

$this->privates['massive_search.command.init'] = $instance = new \Massive\Bundle\SearchBundle\Command\InitCommand(($this->services['massive_search.adapter.zend_lucene'] ?? $this->load('getMassiveSearch_Adapter_ZendLuceneService.php')));

$instance->setName('massive:search:init');

return $instance;
