<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'massive_search.localization_decorator' shared service.

return $this->privates['massive_search.localization_decorator'] = new \Massive\Bundle\SearchBundle\Search\Decorator\LocalizationDecorator(($this->privates['massive_search.index_name_decorator'] ?? $this->load('getMassiveSearch_IndexNameDecoratorService.php')));
