<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'massive_search.events.zend_rebuild' shared service.

return $this->privates['massive_search.events.zend_rebuild'] = new \Massive\Bundle\SearchBundle\Search\EventListener\ZendRebuildSubscriber(($this->services['massive_search.adapter.zend_lucene'] ?? $this->load('getMassiveSearch_Adapter_ZendLuceneService.php')), ($this->privates['massive_search.prefix_decorator'] ?? $this->load('getMassiveSearch_PrefixDecoratorService.php')));
