<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'massive_search.converter.date_converter' shared service.

return $this->privates['massive_search.converter.date_converter'] = new \Massive\Bundle\SearchBundle\Search\Converter\Types\DateConverter();
