<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'massive_search.search.event_subscriber.purge_subscriber' shared service.

return $this->privates['massive_search.search.event_subscriber.purge_subscriber'] = new \Massive\Bundle\SearchBundle\Search\EventSubscriber\PurgeSubscriber(($this->services['massive_search.search_manager'] ?? $this->load('getMassiveSearch_SearchManagerService.php')));
