<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'massive_search.metadata.field_evaluator' shared service.

return $this->privates['massive_search.metadata.field_evaluator'] = new \Massive\Bundle\SearchBundle\Search\Metadata\FieldEvaluator(($this->privates['massive_search.expression_language'] ?? ($this->privates['massive_search.expression_language'] = new \Massive\Bundle\SearchBundle\Search\ExpressionLanguage\MassiveSearchExpressionLanguage())));
