<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'massive_search.events.deindex_listener' shared service.

return $this->privates['massive_search.events.deindex_listener'] = new \Massive\Bundle\SearchBundle\Search\EventListener\DeindexListener(($this->services['massive_search.search_manager'] ?? $this->load('getMassiveSearch_SearchManagerService.php')));
