<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.public_alias.Doctrine\Bundle\PHPCRBundle\Command\NodeDumpCommand' shared service.

$this->services['console.command.public_alias.Doctrine\\Bundle\\PHPCRBundle\\Command\\NodeDumpCommand'] = $instance = new \Doctrine\Bundle\PHPCRBundle\Command\NodeDumpCommand();

$instance->setConsoleDumper(($this->privates['doctrine_phpcr.console_dumper'] ?? ($this->privates['doctrine_phpcr.console_dumper'] = new \PHPCR\Util\Console\Helper\PhpcrConsoleDumperHelper())));

return $instance;
