<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'phpcr_migrations.version_storage' shared service.

return $this->privates['phpcr_migrations.version_storage'] = new \PHPCR\Migrations\VersionStorage(($this->services['sulu_test.doctrine_phpcr.default_session'] ?? $this->getSuluTest_DoctrinePhpcr_DefaultSessionService()), 'jcr:versions');
