<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'phpcr_migrations.command.status' shared service.

return $this->services['phpcr_migrations.command.status'] = new \DTL\Bundle\PhpcrMigrations\Command\StatusCommand(($this->privates['phpcr_migrations.version_storage'] ?? $this->load('getPhpcrMigrations_VersionStorageService.php')), ($this->privates['phpcr_migrations.version_finder'] ?? $this->load('getPhpcrMigrations_VersionFinderService.php')));
