<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'phpcr_migrations.version_finder' shared service.

return $this->privates['phpcr_migrations.version_finder'] = new \PHPCR\Migrations\VersionFinder($this->parameters['phpcr_migrations.paths']);
