<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'phpcr_migrations.migrator_factory' shared service.

return $this->privates['phpcr_migrations.migrator_factory'] = new \PHPCR\Migrations\MigratorFactory(($this->privates['phpcr_migrations.version_storage'] ?? $this->load('getPhpcrMigrations_VersionStorageService.php')), ($this->privates['phpcr_migrations.version_finder'] ?? $this->load('getPhpcrMigrations_VersionFinderService.php')), ($this->services['sulu_test.doctrine_phpcr.default_session'] ?? $this->getSuluTest_DoctrinePhpcr_DefaultSessionService()));
