<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'phpcr_migrations.command.migrate' shared service.

return $this->services['phpcr_migrations.command.migrate'] = new \DTL\Bundle\PhpcrMigrations\Command\MigrateCommand(($this->privates['phpcr_migrations.migrator_factory'] ?? $this->load('getPhpcrMigrations_MigratorFactoryService.php')), $this);
