<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_admin.form_metadata_provider' shared service.

return $this->privates['sulu_admin.form_metadata_provider'] = new \Sulu\Bundle\AdminBundle\Metadata\FormMetadata\FormMetadataProvider(($this->privates['sulu_core.expression_language'] ?? $this->load('getSuluCore_ExpressionLanguageService.php')), new RewindableGenerator(function () {
    yield 0 => ($this->services['sulu_form_test.dynamic_form_metadata_loader'] ?? $this->load('getSuluFormTest_DynamicFormMetadataLoaderService.php'));
    yield 1 => ($this->privates['sulu_admin.xml_form_metadata_loader'] ?? $this->load('getSuluAdmin_XmlFormMetadataLoaderService.php'));
    yield 2 => ($this->privates['sulu_admin.structure_form_metadata_loader'] ?? $this->load('getSuluAdmin_StructureFormMetadataLoaderService.php'));
}, 3));
