<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_admin.list_metadata_provider' shared service.

return $this->privates['sulu_admin.list_metadata_provider'] = new \Sulu\Bundle\AdminBundle\Metadata\ListMetadata\ListMetadataProvider(new RewindableGenerator(function () {
    yield 0 => ($this->services['sulu_form_test.dynamic_list_metadata_loader'] ?? $this->load('getSuluFormTest_DynamicListMetadataLoaderService.php'));
    yield 1 => ($this->privates['sulu_admin.xml_list_metadata_loader'] ?? $this->load('getSuluAdmin_XmlListMetadataLoaderService.php'));
}, 2));
