<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_document_manager.command.fixtures_load' shared service.

$this->privates['sulu_document_manager.command.fixtures_load'] = $instance = new \Sulu\Bundle\DocumentManagerBundle\Command\FixturesLoadCommand(($this->privates['sulu_document_manager.data_fixtures.loader'] ?? ($this->privates['sulu_document_manager.data_fixtures.loader'] = new \Sulu\Bundle\DocumentManagerBundle\DataFixtures\DocumentFixtureLoader($this))), ($this->privates['sulu_document_manager.data_fixtures.executor'] ?? $this->load('getSuluDocumentManager_DataFixtures_ExecutorService.php')), ($this->services['kernel'] ?? $this->get('kernel', 1)));

$instance->setName('sulu:document:fixtures:load');

return $instance;
