<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_page.command.maintain_resource_locator' shared service.

$this->privates['sulu_page.command.maintain_resource_locator'] = $instance = new \Sulu\Bundle\PageBundle\Command\MaintainResourceLocatorCommand(($this->services['sulu_core.webspace.webspace_manager'] ?? $this->getSuluCore_Webspace_WebspaceManagerService()), ($this->services['sulu.phpcr.session'] ?? $this->getSulu_Phpcr_SessionService()), ($this->services['sulu_test.doctrine_phpcr.live_session'] ?? $this->getSuluTest_DoctrinePhpcr_LiveSessionService()), ($this->privates['sulu_document_manager.metadata_factory'] ?? $this->getSuluDocumentManager_MetadataFactoryService()), ($this->services['sulu_page.structure.factory'] ?? $this->getSuluPage_Structure_FactoryService()), ($this->services['sulu_document_manager.property_encoder'] ?? $this->getSuluDocumentManager_PropertyEncoderService()));

$instance->setName('sulu:content:resource-locator:maintain');

return $instance;
