<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_media.search.subscriber.media' shared service.

return $this->privates['sulu_media.search.subscriber.media'] = new \Sulu\Bundle\MediaBundle\Search\Subscriber\MediaSearchSubscriber(($this->services['sulu_media.media_manager'] ?? $this->getSuluMedia_MediaManagerService()), ($this->privates['sulu_search.search.factory'] ?? ($this->privates['sulu_search.search.factory'] = new \Sulu\Bundle\SearchBundle\Search\Factory())), $this->parameters['sulu_media.format_manager.mime_types'], 'sulu-100x100', ($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService()));
