<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_custom_urls.serializer.event_subscriber' shared service.

return $this->privates['sulu_custom_urls.serializer.event_subscriber'] = new \Sulu\Bundle\CustomUrlBundle\EventListener\CustomUrlSerializeEventSubscriber(($this->privates['sulu_custom_urls.domain_generator'] ?? $this->load('getSuluCustomUrls_DomainGeneratorService.php')), ($this->services['sulu_security.user_manager'] ?? $this->load('getSuluSecurity_UserManagerService.php')));
