<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_form.form_type' shared service.

return $this->privates['sulu_form.form_type'] = new \Sulu\Bundle\FormBundle\Form\Type\DynamicFormType(($this->privates['sulu_form.dynamic.form_field_type_pool'] ?? $this->getSuluForm_Dynamic_FormFieldTypePoolService()), ($this->privates['sulu_form.checksum'] ?? ($this->privates['sulu_form.checksum'] = new \Sulu\Bundle\FormBundle\Dynamic\Checksum('secret'))));
