<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_security.mask_converter' shared service.

return $this->services['sulu_security.mask_converter'] = new \Sulu\Component\Security\Authorization\MaskConverter($this->parameters['permissions']);
