<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu.repository.route' shared service.

if ($lazyLoad) {
    return $this->services['sulu.repository.route'] = $this->createProxy('RouteRepository_ee5eed9', function () {
        return \RouteRepository_ee5eed9::staticProxyConstructor(function (&$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface $proxy) {
            $wrappedInstance = $this->load('getSulu_Repository_RouteService.php', false);

            $proxy->setProxyInitializer(null);

            return true;
        });
    });
}

$a = ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService());

return new \Sulu\Bundle\RouteBundle\Entity\RouteRepository($a, $a->getClassMetadata('Sulu\\Bundle\\RouteBundle\\Entity\\Route'));
