<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_website.sitemap.xml_renderer' shared service.

return $this->services['sulu_website.sitemap.xml_renderer'] = new \Sulu\Bundle\WebsiteBundle\Sitemap\XmlSitemapRenderer(($this->services['sulu_website.sitemap.pool'] ?? $this->load('getSuluWebsite_Sitemap_PoolService.php')), ($this->services['templating'] ?? $this->load('getTemplatingService.php')));
