<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu.content.webspace_structure_provider' shared service.

return $this->services['sulu.content.webspace_structure_provider'] = new \Sulu\Component\Webspace\StructureProvider\WebspaceStructureProvider(($this->services['twig'] ?? $this->getTwigService()), ($this->services['sulu.content.structure_manager'] ?? $this->getSulu_Content_StructureManagerService()), ($this->privates['sulu.content.webspace_structure_provider.cache'] ?? ($this->privates['sulu.content.webspace_structure_provider.cache'] = new \Doctrine\Common\Cache\FilesystemCache(($this->targetDirs[0].'/sulu/webspace_structures')))));
