<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_document_manager.data_fixtures.loader' shared service.

return $this->privates['sulu_document_manager.data_fixtures.loader'] = new \Sulu\Bundle\DocumentManagerBundle\DataFixtures\DocumentFixtureLoader($this);
