<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_document_manager.document.subscriber.compat.content_mapper' shared service.

return $this->privates['sulu_document_manager.document.subscriber.compat.content_mapper'] = new \Sulu\Component\Content\Document\Subscriber\Compat\ContentMapperSubscriber(($this->services['sulu_document_manager.document_inspector'] ?? $this->getSuluDocumentManager_DocumentInspectorService()), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()), ($this->services['sulu.content.mapper'] ?? $this->getSulu_Content_MapperService()), ($this->services['sulu.util.node_helper'] ?? $this->getSulu_Util_NodeHelperService()), ($this->services['sulu.content.structure_manager'] ?? $this->getSulu_Content_StructureManagerService()));
