<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_admin.admin_pool' shared service.

$this->services['sulu_admin.admin_pool'] = $instance = new \Sulu\Bundle\AdminBundle\Admin\AdminPool();

$a = ($this->services['sulu_security.security_checker'] ?? $this->getSuluSecurity_SecurityCheckerService());
$b = ($this->privates['sulu_admin.route_factory'] ?? ($this->privates['sulu_admin.route_factory'] = new \Sulu\Bundle\AdminBundle\Admin\Routing\RouteBuilderFactory()));
$c = ($this->services['sulu_core.webspace.webspace_manager'] ?? $this->getSuluCore_Webspace_WebspaceManagerService());
$d = ($this->services['router'] ?? $this->getRouterService());
$e = ($this->services['sulu.core.localization_manager'] ?? $this->load('getSulu_Core_LocalizationManagerService.php'));

$instance->addAdmin(new \Sulu\Bundle\FormBundle\Admin\FormAdmin($a, $b, $c));
$instance->addAdmin(new \Sulu\Bundle\SearchBundle\Admin\SearchAdmin($b));
$instance->addAdmin(new \Sulu\Bundle\PageBundle\Admin\PageAdmin($b, $c, $a, ($this->services['sulu.phpcr.session'] ?? $this->getSulu_Phpcr_SessionService()), ($this->privates['sulu_page.teaser.provider_pool'] ?? $this->load('getSuluPage_Teaser_ProviderPoolService.php')), false));
$instance->addAdmin(new \Sulu\Bundle\ContactBundle\Admin\ContactAdmin($b, $a, ($this->services['doctrine'] ?? $this->getDoctrineService())));
$instance->addAdmin(new \Sulu\Bundle\SecurityBundle\Admin\SecurityAdmin($b, $a, $d, ($this->services['translator'] ?? $this->getTranslatorService()), $this->parameters['sulu_admin.resources']));
$instance->addAdmin(new \Sulu\Bundle\WebsiteBundle\Admin\WebsiteAdmin($b, $c, $a, $d));
$instance->addAdmin(new \Sulu\Bundle\TagBundle\Admin\TagAdmin($b, $a));
$instance->addAdmin(new \Sulu\Bundle\MediaBundle\Admin\MediaAdmin($b, $a, $e, $d));
$instance->addAdmin(new \Sulu\Bundle\CategoryBundle\Admin\CategoryAdmin($b, $a, $e));
$instance->addAdmin(new \Sulu\Bundle\SnippetBundle\Admin\SnippetAdmin($b, $a, $c, true));
$instance->addAdmin(new \Sulu\Bundle\CustomUrlBundle\Admin\CustomUrlAdmin($c, $b, $a));
$instance->addAdmin(new \Sulu\Bundle\AudienceTargetingBundle\Admin\AudienceTargetingAdmin($b, ($this->privates['sulu_audience_targeting.rules_collection'] ?? $this->load('getSuluAudienceTargeting_RulesCollectionService.php')), $a));
$instance->addAdmin(new \Sulu\Bundle\PreviewBundle\Admin\PreviewAdmin($d, 500, 'auto'));

return $instance;
