<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_route.command.update_route' shared service.

$this->privates['sulu_route.command.update_route'] = $instance = new \Sulu\Bundle\RouteBundle\Command\UpdateRouteCommand(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->privates['sulu_route.manager.route_manager'] ?? $this->load('getSuluRoute_Manager_RouteManagerService.php')));

$instance->setName('sulu:route:update');

return $instance;
