<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_resource_segment.document.subscriber.resource_segment' shared service.

return $this->privates['sulu_resource_segment.document.subscriber.resource_segment'] = new \Sulu\Component\Content\Document\Subscriber\ResourceSegmentSubscriber(($this->services['sulu_document_manager.property_encoder'] ?? $this->getSuluDocumentManager_PropertyEncoderService()), ($this->services['sulu_document_manager.document_manager'] ?? $this->getSuluDocumentManager_DocumentManagerService()), ($this->services['sulu_document_manager.document_inspector'] ?? $this->getSuluDocumentManager_DocumentInspectorService()), ($this->privates['sulu.content.resource_locator.strategy_pool'] ?? $this->getSulu_Content_ResourceLocator_StrategyPoolService()), ($this->services['sulu_test.doctrine_phpcr.default_session'] ?? $this->getSuluTest_DoctrinePhpcr_DefaultSessionService()), ($this->services['sulu_test.doctrine_phpcr.live_session'] ?? $this->getSuluTest_DoctrinePhpcr_LiveSessionService()));
