<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_media.format_cache_clearer' shared service.

$this->privates['sulu_media.format_cache_clearer'] = $instance = new \Sulu\Bundle\MediaBundle\Media\FormatCache\FormatCacheClearer();

$instance->add(($this->privates['sulu_media.format_cache'] ?? $this->getSuluMedia_FormatCacheService()), 'local');

return $instance;
