<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_route.routing.defaults_provider' shared service.

return $this->privates['sulu_route.routing.defaults_provider'] = new \Sulu\Bundle\RouteBundle\Routing\Defaults\RouteDefaultsProvider([0 => ($this->privates['sulu_page.preview.defaults_provider'] ?? $this->load('getSuluPage_Preview_DefaultsProviderService.php'))]);
