<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_form.reference_store.form' shared service.

return $this->privates['sulu_form.reference_store.form'] = new \Sulu\Bundle\WebsiteBundle\ReferenceStore\ReferenceStore();
