<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_media.command.type_update' shared service.

$this->privates['sulu_media.command.type_update'] = $instance = new \Sulu\Bundle\MediaBundle\Command\MediaTypeUpdateCommand(($this->privates['sulu_media.type_manager'] ?? $this->getSuluMedia_TypeManagerService()), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()));

$instance->setName('sulu:media:type:update');

return $instance;
