<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_page.permission_listener' shared service.

return $this->privates['sulu_page.permission_listener'] = new \Sulu\Bundle\PageBundle\Search\EventListener\PermissionListener(($this->services['sulu_document_manager.document_manager'] ?? $this->getSuluDocumentManager_DocumentManagerService()), ($this->services['massive_search.search_manager'] ?? $this->load('getMassiveSearch_SearchManagerService.php')));
