<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_form.dynamic_controller' shared service.

return $this->services['sulu_form.dynamic_controller'] = new \Sulu\Bundle\FormBundle\Controller\DynamicController(($this->privates['sulu_form.repository.dynamic'] ?? $this->load('getSuluForm_Repository_DynamicService.php')), ($this->privates['sulu_form.list_builder.dynamic_list_factory'] ?? $this->load('getSuluForm_ListBuilder_DynamicListFactoryService.php')), ($this->services['sulu_media.media_manager'] ?? $this->getSuluMedia_MediaManagerService()), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->privates['sulu_form.repository.form'] ?? $this->getSuluForm_Repository_FormService()), ($this->services['fos_rest.view_handler'] ?? $this->load('getFosRest_ViewHandlerService.php')));
