<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_custom_urls.manager' shared service.

return $this->services['sulu_custom_urls.manager'] = new \Sulu\Component\CustomUrl\Manager\CustomUrlManager(($this->services['sulu_document_manager.document_manager'] ?? $this->getSuluDocumentManager_DocumentManagerService()), ($this->services['sulu_document_manager.document_inspector'] ?? $this->getSuluDocumentManager_DocumentInspectorService()), ($this->privates['sulu_custom_urls.repository'] ?? $this->load('getSuluCustomUrls_RepositoryService.php')), ($this->privates['sulu_document_manager.metadata_factory'] ?? $this->getSuluDocumentManager_MetadataFactoryService()), ($this->privates['sulu_document_manager.path_builder'] ?? $this->load('getSuluDocumentManager_PathBuilderService.php')), ($this->services['sulu_core.webspace.webspace_manager'] ?? $this->getSuluCore_Webspace_WebspaceManagerService()), 'test');
