<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_page.compat.serializer.handler.page_bridge' shared service.

return $this->privates['sulu_page.compat.serializer.handler.page_bridge'] = new \Sulu\Component\Content\Compat\Serializer\PageBridgeHandler(($this->services['sulu_document_manager.document_inspector'] ?? $this->getSuluDocumentManager_DocumentInspectorService()), ($this->services['sulu_page.compat.structure.legacy_property_factory'] ?? $this->getSuluPage_Compat_Structure_LegacyPropertyFactoryService()), ($this->services['sulu_page.structure.factory'] ?? $this->getSuluPage_Structure_FactoryService()));
