<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_contact.content.contact_account_selection' shared service.

return $this->services['sulu_contact.content.contact_account_selection'] = new \Sulu\Bundle\ContactBundle\Content\Types\ContactAccountSelection(($this->services['sulu_contact.contact_manager'] ?? $this->load('getSuluContact_ContactManagerService.php')), ($this->services['sulu_contact.account_manager'] ?? $this->load('getSuluContact_AccountManagerService.php')), ($this->services['jms_serializer'] ?? $this->getJmsSerializerService()), ($this->privates['sulu_contact.util.id_converter'] ?? ($this->privates['sulu_contact.util.id_converter'] = new \Sulu\Bundle\ContactBundle\Util\CustomerIdConverter())), ($this->services['sulu_contact.util.index_comparator'] ?? ($this->services['sulu_contact.util.index_comparator'] = new \Sulu\Bundle\ContactBundle\Util\IndexComparator())), ($this->privates['sulu_contact.reference_store.account'] ?? ($this->privates['sulu_contact.reference_store.account'] = new \Sulu\Bundle\WebsiteBundle\ReferenceStore\ReferenceStore())), ($this->privates['sulu_contact.reference_store.contact'] ?? ($this->privates['sulu_contact.reference_store.contact'] = new \Sulu\Bundle\WebsiteBundle\ReferenceStore\ReferenceStore())));
