<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_admin.structure_form_metadata_loader' shared service.

return $this->privates['sulu_admin.structure_form_metadata_loader'] = new \Sulu\Bundle\AdminBundle\Metadata\FormMetadata\StructureFormMetadataLoader(($this->services['sulu_page.structure.factory'] ?? $this->getSuluPage_Structure_FactoryService()), ($this->privates['sulu_admin.form_metadata.form_metadata_mapper'] ?? ($this->privates['sulu_admin.form_metadata.form_metadata_mapper'] = new \Sulu\Bundle\AdminBundle\FormMetadata\FormMetadataMapper())), $this->parameters['sulu_core.locales'], ($this->targetDirs[0].'/sulu/form-structures'), true);
