<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_document_manager.command.subscriber_debug' shared service.

$this->privates['sulu_document_manager.command.subscriber_debug'] = $instance = new \Sulu\Bundle\DocumentManagerBundle\Command\SubscriberDebugCommand(($this->privates['sulu_document_manager.event_dispatcher.standard'] ?? $this->getSuluDocumentManager_EventDispatcher_StandardService()));

$instance->setName('sulu:document:subscriber:debug');

return $instance;
