<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_core.rest.datetime_handler' shared service.

return $this->privates['sulu_core.rest.datetime_handler'] = new \Sulu\Component\Rest\Handler\DateHandler();
