<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_security.profile_controller' shared service.

return $this->services['sulu_security.profile_controller'] = new \Sulu\Bundle\SecurityBundle\Controller\ProfileController(($this->services['security.token_storage'] ?? ($this->services['security.token_storage'] = new \Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage())), ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->services['fos_rest.view_handler'] ?? $this->load('getFosRest_ViewHandlerService.php')), ($this->services['sulu_security.user_setting_repository'] ?? $this->load('getSuluSecurity_UserSettingRepositoryService.php')), ($this->services['sulu_security.user_manager'] ?? $this->load('getSuluSecurity_UserManagerService.php')));
