<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_page.command.cleanup_history' shared service.

$this->privates['sulu_page.command.cleanup_history'] = $instance = new \Sulu\Bundle\PageBundle\Command\CleanupHistoryCommand(($this->services['sulu.phpcr.session'] ?? $this->getSulu_Phpcr_SessionService()), ($this->services['sulu_test.doctrine_phpcr.default_session'] ?? $this->getSuluTest_DoctrinePhpcr_DefaultSessionService()), ($this->services['sulu_test.doctrine_phpcr.live_session'] ?? $this->getSuluTest_DoctrinePhpcr_LiveSessionService()));

$instance->setName('sulu:content:cleanup-history');

return $instance;
