<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_page.search.reindex.structure_provider' shared service.

return $this->privates['sulu_page.search.reindex.structure_provider'] = new \Sulu\Bundle\PageBundle\Search\Reindex\StructureProvider(($this->services['sulu_document_manager.document_manager'] ?? $this->getSuluDocumentManager_DocumentManagerService()), ($this->services['sulu_document_manager.metadata_factory.base'] ?? $this->getSuluDocumentManager_MetadataFactory_BaseService()), ($this->services['sulu_page.structure.factory'] ?? $this->getSuluPage_Structure_FactoryService()), ($this->services['sulu_document_manager.document_inspector'] ?? $this->getSuluDocumentManager_DocumentInspectorService()), 'admin');
