<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_audience_targeting.content.type.target_group_selection' shared service.

return $this->services['sulu_audience_targeting.content.type.target_group_selection'] = new \Sulu\Bundle\AudienceTargetingBundle\Content\Types\TargetGroupSelection(($this->services['sulu.repository.target_group'] ?? $this->getSulu_Repository_TargetGroupService()));
