<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_page.command.webspace_export' shared service.

$this->privates['sulu_page.command.webspace_export'] = $instance = new \Sulu\Bundle\PageBundle\Command\WebspaceExportCommand(($this->services['sulu_page.export.webspace'] ?? $this->load('getSuluPage_Export_WebspaceService.php')));

$instance->setName('sulu:webspaces:export');

return $instance;
