<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_document_manager.initializer.root_path_purge_initializer' shared service.

return $this->services['sulu_document_manager.initializer.root_path_purge_initializer'] = new \Sulu\Bundle\DocumentManagerBundle\Initializer\RootPathPurgeInitializer(($this->services['doctrine_phpcr'] ?? $this->getDoctrinePhpcrService()), ($this->privates['sulu_document_manager.path_segment_registry'] ?? $this->getSuluDocumentManager_PathSegmentRegistryService()), 'base');
