<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_document_manager.node_helper' shared service.

return $this->privates['sulu_document_manager.node_helper'] = new \Sulu\Component\DocumentManager\NodeHelper();
