<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_page.teaser.serializer.event_subscriber' shared service.

return $this->privates['sulu_page.teaser.serializer.event_subscriber'] = new \Sulu\Bundle\PageBundle\EventListener\TeaserSerializeEventSubscriber(($this->services['sulu_media.media_manager'] ?? $this->getSuluMedia_MediaManagerService()));
