<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_route.chain_generator' shared service.

return $this->privates['sulu_route.chain_generator'] = new \Sulu\Bundle\RouteBundle\Generator\ChainRouteGenerator([], [], ($this->services['sulu.repository.route'] ?? $this->load('getSulu_Repository_RouteService.php')));
