<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu.repository.access_control' shared service.

if ($lazyLoad) {
    return $this->services['sulu.repository.access_control'] = $this->createProxy('AccessControlRepository_b331497', function () {
        return \AccessControlRepository_b331497::staticProxyConstructor(function (&$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface $proxy) {
            $wrappedInstance = $this->load('getSulu_Repository_AccessControlService.php', false);

            $proxy->setProxyInitializer(null);

            return true;
        });
    });
}

$a = ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService());

return new \Sulu\Bundle\SecurityBundle\Entity\AccessControlRepository($a, $a->getClassMetadata('Sulu\\Bundle\\SecurityBundle\\Entity\\AccessControl'));
