<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_media.smart_content.data_provider.media' shared service.

return $this->privates['sulu_media.smart_content.data_provider.media'] = new \Sulu\Component\Media\SmartContent\MediaDataProvider(($this->privates['sulu_media.smart_content.data_provider.media.repository'] ?? $this->load('getSuluMedia_SmartContent_DataProvider_Media_RepositoryService.php')), ($this->services['sulu_media.collection_manager'] ?? $this->getSuluMedia_CollectionManagerService()), ($this->services['jms_serializer'] ?? $this->getJmsSerializerService()), ($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($this->privates['sulu_media.reference_store.media'] ?? ($this->privates['sulu_media.reference_store.media'] = new \Sulu\Bundle\WebsiteBundle\ReferenceStore\ReferenceStore())));
