<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_media.permission_listener' shared service.

return $this->privates['sulu_media.permission_listener'] = new \Sulu\Bundle\MediaBundle\Search\EventListener\PermissionListener(($this->privates['sulu_media.file_version_meta_repository'] ?? $this->load('getSuluMedia_FileVersionMetaRepositoryService.php')), ($this->services['massive_search.search_manager'] ?? $this->load('getMassiveSearch_SearchManagerService.php')));
