<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_website.sitemap.xml_dumper' shared service.

return $this->services['sulu_website.sitemap.xml_dumper'] = new \Sulu\Bundle\WebsiteBundle\Sitemap\XmlSitemapDumper(($this->services['sulu_website.sitemap.xml_renderer'] ?? $this->load('getSuluWebsite_Sitemap_XmlRendererService.php')), ($this->services['sulu_website.sitemap.pool'] ?? $this->load('getSuluWebsite_Sitemap_PoolService.php')), ($this->services['filesystem'] ?? ($this->services['filesystem'] = new \Symfony\Component\Filesystem\Filesystem())), ($this->targetDirs[0].'/sulu/sitemaps'), NULL);
