<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu.content.type.url' shared service.

return $this->services['sulu.content.type.url'] = new \Sulu\Bundle\PageBundle\Content\Types\Url();
