<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_contact.command.recover' shared service.

$this->privates['sulu_contact.command.recover'] = $instance = new \Sulu\Bundle\ContactBundle\Command\AccountRecoverCommand(($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->services['sulu.repository.account'] ?? $this->load('getSulu_Repository_AccountService.php')));

$instance->setName('sulu:contacts:accounts:recover');

return $instance;
