<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_page.search.event_subscriber.structure' shared service.

return $this->privates['sulu_page.search.event_subscriber.structure'] = new \Sulu\Bundle\PageBundle\Search\EventSubscriber\StructureSubscriber(($this->services['massive_search.search_manager'] ?? $this->load('getMassiveSearch_SearchManagerService.php')));
