<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.user_checker' shared service.

return $this->privates['security.user_checker'] = new \Symfony\Component\Security\Core\User\UserChecker();
