<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_page.command.copy_locale' shared service.

$this->privates['sulu_page.command.copy_locale'] = $instance = new \Sulu\Bundle\PageBundle\Command\ContentLocaleCopyCommand(($this->services['sulu.content.mapper'] ?? $this->getSulu_Content_MapperService()), ($this->services['sulu_test.doctrine_phpcr.default_session'] ?? $this->getSuluTest_DoctrinePhpcr_DefaultSessionService()), 'i18n');

$instance->setName('sulu:content:locale-copy');

return $instance;
