<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_security.security_context_voter' shared service.

return $this->privates['sulu_security.security_context_voter'] = new \Sulu\Component\Security\Authorization\SecurityContextVoter(($this->privates['sulu_security.access_control_manager'] ?? $this->load('getSuluSecurity_AccessControlManagerService.php')), $this->parameters['permissions']);
