<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_form.list_builder.dynamic_list_factory' shared service.

$this->privates['sulu_form.list_builder.dynamic_list_factory'] = $instance = new \Sulu\Bundle\FormBundle\ListBuilder\DynamicListFactory('simple');

$instance->add(($this->privates['sulu_form.list_builder.dynamic_list_builder'] ?? $this->load('getSuluForm_ListBuilder_DynamicListBuilderService.php')), 'simple');

return $instance;
