<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_security.encoder_factory' shared service.

return $this->services['sulu_security.encoder_factory'] = new \Symfony\Component\Security\Core\Encoder\EncoderFactory(['Sulu\\Bundle\\SecurityBundle\\Entity\\User' => ['class' => 'Symfony\\Component\\Security\\Core\\Encoder\\PlaintextPasswordEncoder', 'arguments' => [0 => false]]]);
