<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_media.command.clear_cache' shared service.

$this->privates['sulu_media.command.clear_cache'] = $instance = new \Sulu\Bundle\MediaBundle\Command\ClearCacheCommand(($this->privates['sulu_media.format_cache_clearer'] ?? $this->load('getSuluMedia_FormatCacheClearerService.php')));

$instance->setName('sulu:media:format:cache:clear');

return $instance;
