<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_preview.preview.kernel_factory' shared service.

return $this->privates['sulu_preview.preview.kernel_factory'] = new \Sulu\Bundle\PreviewBundle\Preview\Renderer\WebsiteKernelFactory();
