<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_contact.account_manager' shared service.

return $this->services['sulu_contact.account_manager'] = new \Sulu\Bundle\ContactBundle\Contact\AccountManager(($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->services['sulu_tag.tag_manager'] ?? $this->getSuluTag_TagManagerService()), ($this->services['sulu_media.media_manager'] ?? $this->getSuluMedia_MediaManagerService()), ($this->services['sulu_contact.account_factory'] ?? ($this->services['sulu_contact.account_factory'] = new \Sulu\Bundle\ContactBundle\Contact\AccountFactory('Sulu\\Bundle\\ContactBundle\\Entity\\Account'))), ($this->services['sulu.repository.account'] ?? $this->load('getSulu_Repository_AccountService.php')), ($this->services['sulu.repository.contact'] ?? $this->getSulu_Repository_ContactService()), ($this->services['sulu.repository.media'] ?? $this->getSulu_Repository_MediaService()), 'Sulu\\Bundle\\ContactBundle\\Entity\\Account');
