<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_tag.search.tags_converter' shared service.

return $this->privates['sulu_tag.search.tags_converter'] = new \Sulu\Bundle\TagBundle\Search\TagsConverter(($this->services['sulu_tag.tag_manager'] ?? $this->getSuluTag_TagManagerService()));
