<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_admin.schema_handler' shared service.

return $this->privates['sulu_admin.schema_handler'] = new \Sulu\Bundle\AdminBundle\Serializer\Handler\SchemaHandler();
