<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_page.node_repository' shared service.

return $this->services['sulu_page.node_repository'] = new \Sulu\Bundle\PageBundle\Repository\NodeRepository(($this->services['sulu.content.mapper'] ?? $this->getSulu_Content_MapperService()), ($this->services['sulu.phpcr.session'] ?? $this->getSulu_Phpcr_SessionService()), ($this->services['sulu_security.user_manager'] ?? $this->load('getSuluSecurity_UserManagerService.php')), ($this->services['sulu_core.webspace.webspace_manager'] ?? $this->getSuluCore_Webspace_WebspaceManagerService()), ($this->privates['sulu_page.smart_content.data_provider.content.query_builder'] ?? $this->load('getSuluPage_SmartContent_DataProvider_Content_QueryBuilderService.php')), ($this->privates['sulu.content.query_executor'] ?? $this->getSulu_Content_QueryExecutorService()), ($this->privates['sulu_security.access_control_manager'] ?? $this->load('getSuluSecurity_AccessControlManagerService.php')), ($this->services['security.token_storage'] ?? ($this->services['security.token_storage'] = new \Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage())));
