<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_snippet.smart_content.snippet_data_provider' shared service.

return $this->privates['sulu_snippet.smart_content.snippet_data_provider'] = new \Sulu\Bundle\SnippetBundle\Content\SnippetDataProvider(($this->privates['sulu.content.query_executor'] ?? $this->getSulu_Content_QueryExecutorService()), ($this->privates['sulu_snippet.smart_content.data_provider.query_builder'] ?? $this->load('getSuluSnippet_SmartContent_DataProvider_QueryBuilderService.php')), ($this->services['sulu.util.node_helper'] ?? $this->getSulu_Util_NodeHelperService()), ($this->privates['sulu_page.smart_content.data_provider.content.proxy_factory'] ?? $this->load('getSuluPage_SmartContent_DataProvider_Content_ProxyFactoryService.php')), ($this->services['sulu_document_manager.document_manager'] ?? $this->getSuluDocumentManager_DocumentManagerService()), ($this->services['sulu_snippet.reference_store.snippet'] ?? ($this->services['sulu_snippet.reference_store.snippet'] = new \Sulu\Bundle\WebsiteBundle\ReferenceStore\ReferenceStore())));
