<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_page.document.serializer.subscriber.shadow_locale_behavior' shared service.

return $this->privates['sulu_page.document.serializer.subscriber.shadow_locale_behavior'] = new \Sulu\Bundle\PageBundle\Serializer\Subscriber\ShadowLocaleSubscriber(($this->services['sulu_document_manager.document_inspector'] ?? $this->getSuluDocumentManager_DocumentInspectorService()), ($this->privates['sulu_document_manager.document_registry'] ?? ($this->privates['sulu_document_manager.document_registry'] = new \Sulu\Component\DocumentManager\DocumentRegistry('en'))));
