<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_document_manager.subscriber.behavior.path.explicit' shared service.

return $this->privates['sulu_document_manager.subscriber.behavior.path.explicit'] = new \Sulu\Component\DocumentManager\Subscriber\Behavior\Path\ExplicitSubscriber(($this->privates['sulu_document_manager.node_manager'] ?? $this->getSuluDocumentManager_NodeManagerService()));
