<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_route.content_type' shared service.

return $this->services['sulu_route.content_type'] = new \Sulu\Bundle\RouteBundle\Content\Type\RouteContentType();
