<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_custom_urls.url_provider' shared service.

return $this->privates['sulu_custom_urls.url_provider'] = new \Sulu\Component\CustomUrl\WebspaceCustomUrlProvider(($this->services['sulu_custom_urls.manager'] ?? $this->load('getSuluCustomUrls_ManagerService.php')));
