<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_snippet.command.import' shared service.

$this->privates['sulu_snippet.command.import'] = $instance = new \Sulu\Bundle\SnippetBundle\Command\SnippetImportCommand(($this->services['sulu_snippet.import.snippet'] ?? $this->load('getSuluSnippet_Import_SnippetService.php')), ($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService()));

$instance->setName('sulu:snippet:import');

return $instance;
