<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_audience_targeting.rules.os' shared service.

return $this->privates['sulu_audience_targeting.rules.os'] = new \Sulu\Bundle\AudienceTargetingBundle\Rule\OperatingSystemRule(($this->privates['sulu_audience_targeting.device_detector'] ?? ($this->privates['sulu_audience_targeting.device_detector'] = new \DeviceDetector\DeviceDetector())), ($this->services['translator'] ?? $this->getTranslatorService()));
