<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_security.security_systems_select_helper' shared service.

return $this->services['sulu_security.security_systems_select_helper'] = new \Sulu\Bundle\SecurityBundle\Admin\Helper\SecuritySystemsSelect(($this->services['sulu_admin.admin_pool'] ?? $this->load('getSuluAdmin_AdminPoolService.php')), 'Sulu');
