<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_document_manager.subscriber.behavior.filing' shared service.

return $this->privates['sulu_document_manager.subscriber.behavior.filing'] = new \Sulu\Component\Content\Document\Subscriber\StructureTypeFilingSubscriber(($this->services['sulu_test.doctrine_phpcr.default_session'] ?? $this->getSuluTest_DoctrinePhpcr_DefaultSessionService()), ($this->services['sulu_test.doctrine_phpcr.live_session'] ?? $this->getSuluTest_DoctrinePhpcr_LiveSessionService()));
