<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_page.command.validate_pages' shared service.

$this->privates['sulu_page.command.validate_pages'] = $instance = new \Sulu\Bundle\PageBundle\Command\ValidatePagesCommand(($this->services['sulu_test.doctrine_phpcr.default_session'] ?? $this->getSuluTest_DoctrinePhpcr_DefaultSessionService()), ($this->services['sulu_core.webspace.webspace_manager'] ?? $this->getSuluCore_Webspace_WebspaceManagerService()), ($this->services['sulu.content.structure_manager'] ?? $this->getSulu_Content_StructureManagerService()), ($this->services['sulu.content.webspace_structure_provider'] ?? $this->load('getSulu_Content_WebspaceStructureProviderService.php')));

$instance->setName('sulu:content:validate');

return $instance;
