<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_page.resource_locator_controller' shared service.

return $this->services['sulu_page.resource_locator_controller'] = new \Sulu\Bundle\PageBundle\Controller\ResourcelocatorController(($this->privates['sulu.content.resource_locator.strategy_pool'] ?? $this->getSulu_Content_ResourceLocator_StrategyPoolService()), ($this->services['fos_rest.view_handler'] ?? $this->load('getFosRest_ViewHandlerService.php')));
