<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_admin.route_factory' shared service.

return $this->privates['sulu_admin.route_factory'] = new \Sulu\Bundle\AdminBundle\Admin\Routing\RouteBuilderFactory();
