<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_preview.preview_controller' shared service.

return $this->services['sulu_preview.preview_controller'] = new \Sulu\Bundle\PreviewBundle\Controller\PreviewController(($this->privates['sulu_preview.preview'] ?? $this->load('getSuluPreview_PreviewService.php')), ($this->services['security.token_storage'] ?? ($this->services['security.token_storage'] = new \Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage())), ($this->services['profiler'] ?? $this->getProfilerService()));
