<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_security.command.create_role' shared service.

$this->privates['sulu_security.command.create_role'] = $instance = new \Sulu\Bundle\SecurityBundle\Command\CreateRoleCommand(($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->services['sulu.repository.role'] ?? $this->load('getSulu_Repository_RoleService.php')), ($this->services['sulu_admin.admin_pool'] ?? $this->load('getSuluAdmin_AdminPoolService.php')));

$instance->setName('sulu:security:role:create');

return $instance;
