<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_page.document_manager.content_initializer' shared service.

return $this->services['sulu_page.document_manager.content_initializer'] = new \Sulu\Bundle\PageBundle\DocumentManager\ContentInitializer(($this->services['doctrine_phpcr'] ?? $this->getDoctrinePhpcrService()), 'i18n');
