<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_snippet.smart_content.data_provider.query_builder' shared service.

return $this->privates['sulu_snippet.smart_content.data_provider.query_builder'] = new \Sulu\Bundle\SnippetBundle\Content\SnippetQueryBuilder(($this->services['sulu.content.structure_manager'] ?? $this->getSulu_Content_StructureManagerService()), ($this->services['sulu_page.extension.manager'] ?? $this->getSuluPage_Extension_ManagerService()), ($this->services['sulu.phpcr.session'] ?? $this->getSulu_Phpcr_SessionService()), 'i18n');
