<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_category.command.recover' shared service.

$this->privates['sulu_category.command.recover'] = $instance = new \Sulu\Bundle\CategoryBundle\Command\RecoverCommand(($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->services['sulu.repository.category'] ?? $this->getSulu_Repository_CategoryService()));

$instance->setName('sulu:categories:recover');

return $instance;
