<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.authentication.provider.dao.test' shared service.

return $this->privates['security.authentication.provider.dao.test'] = new \Symfony\Component\Security\Core\Authentication\Provider\DaoAuthenticationProvider(($this->services['test_user_provider'] ?? $this->load('getTestUserProviderService.php')), ($this->privates['security.user_checker'] ?? ($this->privates['security.user_checker'] = new \Symfony\Component\Security\Core\User\UserChecker())), 'test', ($this->services['sulu_security.encoder_factory'] ?? $this->load('getSuluSecurity_EncoderFactoryService.php')), true);
