<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.firewall.map.config.test' shared service.

return $this->privates['security.firewall.map.config.test'] = new \Symfony\Bundle\SecurityBundle\Security\FirewallConfig('test', 'security.user_checker', NULL, true, false, 'test_user_provider', 'test', 'security.authentication.basic_entry_point.test', NULL, NULL, [0 => 'http_basic'], NULL);
