<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_page.command.dump_content_types' shared service.

$this->privates['sulu_page.command.dump_content_types'] = $instance = new \Sulu\Bundle\PageBundle\Command\ContentTypesDumpCommand();

$instance->setName('sulu:content:types:dump');

return $instance;
