<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu.content.type.page_selection' shared service.

return $this->services['sulu.content.type.page_selection'] = new \Sulu\Bundle\PageBundle\Content\Types\PageSelection(($this->privates['sulu.content.query_executor'] ?? $this->getSulu_Content_QueryExecutorService()), ($this->privates['sulu_page.smart_content.data_provider.content.query_builder'] ?? $this->load('getSuluPage_SmartContent_DataProvider_Content_QueryBuilderService.php')), ($this->privates['sulu_page.reference_store.content'] ?? ($this->privates['sulu_page.reference_store.content'] = new \Sulu\Bundle\WebsiteBundle\ReferenceStore\ReferenceStore())), true);
