<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_page.teaser_controller' shared service.

return $this->services['sulu_page.teaser_controller'] = new \Sulu\Bundle\PageBundle\Controller\TeaserController(($this->privates['sulu_page.teaser.manager'] ?? $this->load('getSuluPage_Teaser_ManagerService.php')));
