<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_page.command.webspace_import' shared service.

$this->privates['sulu_page.command.webspace_import'] = $instance = new \Sulu\Bundle\PageBundle\Command\WebspaceImportCommand(($this->services['sulu_page.import.webspace'] ?? $this->load('getSuluPage_Import_WebspaceService.php')), ($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService()));

$instance->setName('sulu:webspaces:import');

return $instance;
