<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_document_manager.routing.version_loader' shared service.

return $this->privates['sulu_document_manager.routing.version_loader'] = new \Sulu\Bundle\DocumentManagerBundle\Routing\Loader\VersionRouteLoader(false);
