<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_document_manager.document.subscriber.security' shared service.

return $this->privates['sulu_document_manager.document.subscriber.security'] = new \Sulu\Component\Content\Document\Subscriber\SecuritySubscriber($this->parameters['sulu_security.permissions']);
