<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_preview.preview.renderer' shared service.

return $this->privates['sulu_preview.preview.renderer'] = new \Sulu\Bundle\PreviewBundle\Preview\Renderer\PreviewRenderer(($this->privates['sulu_route.routing.defaults_provider'] ?? $this->load('getSuluRoute_Routing_DefaultsProviderService.php')), ($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($this->privates['sulu_preview.preview.kernel_factory'] ?? ($this->privates['sulu_preview.preview.kernel_factory'] = new \Sulu\Bundle\PreviewBundle\Preview\Renderer\WebsiteKernelFactory())), ($this->services['sulu_core.webspace.webspace_manager'] ?? $this->getSuluCore_Webspace_WebspaceManagerService()), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()), ($this->privates['sulu_core.webspace.webspace_manager.url_replacer'] ?? ($this->privates['sulu_core.webspace.webspace_manager.url_replacer'] = new \Sulu\Component\Webspace\Url\Replacer())), [], 'test', (($this->hasParameter("sulu_audience_targeting.headers.target_group")) ? ($this->getParameter("sulu_audience_targeting.headers.target_group")) : (null)));
