<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_form_test.dynamic_form_metadata_loader' shared service.

return $this->services['sulu_form_test.dynamic_form_metadata_loader'] = new \Sulu\Bundle\FormBundle\Metadata\DynamicFormMetadataLoader(($this->privates['sulu_form.dynamic.form_field_type_pool'] ?? $this->getSuluForm_Dynamic_FormFieldTypePoolService()), ($this->privates['sulu_form.metadata.properties_xml_loader'] ?? $this->load('getSuluForm_Metadata_PropertiesXmlLoaderService.php')), ($this->privates['sulu_admin.form_metadata.form_xml_loader'] ?? $this->load('getSuluAdmin_FormMetadata_FormXmlLoaderService.php')), ($this->privates['sulu_admin.form_metadata.form_metadata_mapper'] ?? ($this->privates['sulu_admin.form_metadata.form_metadata_mapper'] = new \Sulu\Bundle\AdminBundle\FormMetadata\FormMetadataMapper())), ($this->services['translator'] ?? $this->getTranslatorService()), ($this->targetDirs[0].'/sulu-form-bundle/forms'), true);
