<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_website.sitemap.pages_provider' shared service.

return $this->privates['sulu_website.sitemap.pages_provider'] = new \Sulu\Bundle\WebsiteBundle\Sitemap\Provider\PagesSitemapProvider(($this->services['sulu_page.content_repository'] ?? $this->getSuluPage_ContentRepositoryService()), ($this->services['sulu_core.webspace.webspace_manager'] ?? $this->getSuluCore_Webspace_WebspaceManagerService()));
