<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_document_manager.suscriber.behavior.parent' shared service.

return $this->privates['sulu_document_manager.suscriber.behavior.parent'] = new \Sulu\Component\DocumentManager\Subscriber\Behavior\Mapping\ParentSubscriber(($this->privates['sulu_document_manager.proxy_factory'] ?? $this->getSuluDocumentManager_ProxyFactoryService()), ($this->services['sulu_document_manager.document_inspector'] ?? $this->getSuluDocumentManager_DocumentInspectorService()), ($this->services['sulu_document_manager.document_manager'] ?? $this->getSuluDocumentManager_DocumentManagerService()));
