<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_admin.form_metadata.form_xml_loader' shared service.

return $this->privates['sulu_admin.form_metadata.form_xml_loader'] = new \Sulu\Bundle\AdminBundle\FormMetadata\FormXmlLoader(($this->privates['sulu_page.structure.properties_xml_parser'] ?? $this->getSuluPage_Structure_PropertiesXmlParserService()), ($this->privates['sulu_page.structure.schema_xml_parser'] ?? ($this->privates['sulu_page.structure.schema_xml_parser'] = new \Sulu\Component\Content\Metadata\Parser\SchemaXmlParser())), $this->parameters['sulu_core.locales'], ($this->privates['sulu_admin.form_metadata.form_metadata_mapper'] ?? ($this->privates['sulu_admin.form_metadata.form_metadata_mapper'] = new \Sulu\Bundle\AdminBundle\FormMetadata\FormMetadataMapper())));
