<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_page.command.validate_webspaces' shared service.

$this->privates['sulu_page.command.validate_webspaces'] = $instance = new \Sulu\Bundle\PageBundle\Command\ValidateWebspacesCommand(($this->services['twig'] ?? $this->getTwigService()), ($this->services['sulu_page.structure.factory'] ?? $this->getSuluPage_Structure_FactoryService()), ($this->services['sulu_page.controller_name_converter'] ?? ($this->services['sulu_page.controller_name_converter'] = new \Symfony\Bundle\FrameworkBundle\Controller\ControllerNameParser(($this->services['kernel'] ?? $this->get('kernel', 1))))), ($this->services['sulu.content.structure_manager'] ?? $this->getSulu_Content_StructureManagerService()), ($this->services['sulu.content.webspace_structure_provider'] ?? $this->load('getSulu_Content_WebspaceStructureProviderService.php')), ($this->services['sulu_core.webspace.webspace_manager'] ?? $this->getSuluCore_Webspace_WebspaceManagerService()), NULL);

$instance->setName('sulu:content:validate:webspaces');

return $instance;
