<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_search.index_configuration_provider' shared service.

return $this->privates['sulu_search.index_configuration_provider'] = new \Sulu\Bundle\SearchBundle\Search\Configuration\IndexConfigurationProvider(($this->services['translator'] ?? $this->getTranslatorService()), $this->parameters['sulu_search.indexes']);
