<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_snippet.command.export' shared service.

$this->privates['sulu_snippet.command.export'] = $instance = new \Sulu\Bundle\SnippetBundle\Command\SnippetExportCommand(($this->services['sulu_snippet.export.snippet'] ?? $this->load('getSuluSnippet_Export_SnippetService.php')));

$instance->setName('sulu:snippet:export');

return $instance;
