<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_media.doctrine.invalidation_listener' shared service.

return $this->privates['sulu_media.doctrine.invalidation_listener'] = new \Sulu\Bundle\MediaBundle\EventListener\CacheInvalidationListener(NULL);
