<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_location.content.type.location' shared service.

return $this->services['sulu_location.content.type.location'] = new \Sulu\Bundle\LocationBundle\Content\Types\LocationContentType(($this->services['sulu_page.node_repository'] ?? $this->load('getSuluPage_NodeRepositoryService.php')), ($this->privates['sulu_location.map_manager'] ?? $this->load('getSuluLocation_MapManagerService.php')), 'nominatim');
