<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_snippet.export.snippet' shared service.

return $this->services['sulu_snippet.export.snippet'] = new \Sulu\Component\Snippet\Export\SnippetExport(($this->services['templating'] ?? $this->load('getTemplatingService.php')), ($this->services['sulu_snippet.repository'] ?? $this->load('getSuluSnippet_RepositoryService.php')), ($this->services['sulu_document_manager.document_manager'] ?? $this->getSuluDocumentManager_DocumentManagerService()), ($this->services['sulu_document_manager.document_inspector'] ?? $this->getSuluDocumentManager_DocumentInspectorService()), ($this->privates['sulu_page.export.manager'] ?? $this->getSuluPage_Export_ManagerService()), $this->parameters['sulu_snippet.export.snippet.formats']);
