<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_admin.form_metadata.form_metadata_mapper' shared service.

return $this->privates['sulu_admin.form_metadata.form_metadata_mapper'] = new \Sulu\Bundle\AdminBundle\FormMetadata\FormMetadataMapper();
