<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'serializer.normalizer.object' shared service.

return $this->privates['serializer.normalizer.object'] = new \Symfony\Component\Serializer\Normalizer\ObjectNormalizer(($this->privates['serializer.mapping.class_metadata_factory'] ?? $this->load('getSerializer_Mapping_ClassMetadataFactoryService.php')), ($this->privates['serializer.name_converter.metadata_aware'] ?? $this->load('getSerializer_NameConverter_MetadataAwareService.php')), ($this->privates['property_accessor'] ?? $this->load('getPropertyAccessorService.php')), NULL, ($this->privates['serializer.mapping.class_discriminator_resolver'] ?? $this->load('getSerializer_Mapping_ClassDiscriminatorResolverService.php')), NULL, []);
