<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_contact.customer_manager' shared service.

return $this->services['sulu_contact.customer_manager'] = new \Sulu\Bundle\ContactBundle\Contact\CustomerManager(($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->privates['sulu_contact.util.id_converter'] ?? ($this->privates['sulu_contact.util.id_converter'] = new \Sulu\Bundle\ContactBundle\Util\CustomerIdConverter())), ($this->services['sulu_contact.util.index_comparator'] ?? ($this->services['sulu_contact.util.index_comparator'] = new \Sulu\Bundle\ContactBundle\Util\IndexComparator())), 'Sulu\\Bundle\\ContactBundle\\Entity\\Contact', 'Sulu\\Bundle\\ContactBundle\\Entity\\Account');
