<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_admin.metadata_provider_registry' shared service.

$this->privates['sulu_admin.metadata_provider_registry'] = $instance = new \Sulu\Bundle\AdminBundle\Metadata\MetadataProviderRegistry();

$instance->addMetadataProvider('form', ($this->privates['sulu_admin.form_metadata_provider'] ?? $this->load('getSuluAdmin_FormMetadataProviderService.php')));
$instance->addMetadataProvider('list', ($this->privates['sulu_admin.list_metadata_provider'] ?? $this->load('getSuluAdmin_ListMetadataProviderService.php')));

return $instance;
