<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_core.list_builder.field_descriptor_factory' shared service.

return $this->services['sulu_core.list_builder.field_descriptor_factory'] = new \Sulu\Component\Rest\ListBuilder\Metadata\FieldDescriptorFactory(($this->privates['sulu_core.list_builder.metadata.provider.list'] ?? $this->load('getSuluCore_ListBuilder_Metadata_Provider_ListService.php')), $this->parameters['sulu_admin.lists.directories'], ($this->targetDirs[0].'/sulu/field_descriptor'), true);
