<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_security.command.create_user' shared service.

$this->privates['sulu_security.command.create_user'] = $instance = new \Sulu\Bundle\SecurityBundle\Command\CreateUserCommand(($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->services['sulu.repository.user'] ?? $this->getSulu_Repository_UserService()), ($this->services['sulu.repository.role'] ?? $this->load('getSulu_Repository_RoleService.php')), ($this->services['sulu.repository.contact'] ?? $this->getSulu_Repository_ContactService()), ($this->services['sulu.core.localization_manager'] ?? $this->load('getSulu_Core_LocalizationManagerService.php')), ($this->services['sulu_security.salt_generator'] ?? ($this->services['sulu_security.salt_generator'] = new \Sulu\Component\Security\Authentication\SaltGenerator())), ($this->services['sulu_security.encoder_factory'] ?? $this->load('getSuluSecurity_EncoderFactoryService.php')), $this->parameters['sulu_core.locales']);

$instance->setName('sulu:security:user:create');

return $instance;
