<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_tag.content.type.tag_selection' shared service.

return $this->services['sulu_tag.content.type.tag_selection'] = new \Sulu\Bundle\TagBundle\Content\Types\TagSelection(($this->services['sulu_tag.tag_manager'] ?? $this->getSuluTag_TagManagerService()));
