<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_website.analytics.manager' shared service.

return $this->services['sulu_website.analytics.manager'] = new \Sulu\Bundle\WebsiteBundle\Analytics\AnalyticsManager(($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->privates['sulu_website.analytics.repository'] ?? $this->load('getSuluWebsite_Analytics_RepositoryService.php')), ($this->privates['sulu_website.domains.repository'] ?? $this->load('getSuluWebsite_Domains_RepositoryService.php')), 'test');
