<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_form.content_type.single_form_selection' shared service.

return $this->services['sulu_form.content_type.single_form_selection'] = new \Sulu\Bundle\FormBundle\Content\Types\SingleFormSelection('SuluFormBundle:Template:content-types/form_select_simple.html.twig', ($this->privates['sulu_form.repository.form'] ?? $this->getSuluForm_Repository_FormService()), ($this->privates['sulu_form.builder'] ?? $this->getSuluForm_BuilderService()), ($this->privates['sulu_form.reference_store.form'] ?? ($this->privates['sulu_form.reference_store.form'] = new \Sulu\Bundle\WebsiteBundle\ReferenceStore\ReferenceStore())));
