<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_category.content.type.category_selection' shared service.

return $this->services['sulu_category.content.type.category_selection'] = new \Sulu\Bundle\CategoryBundle\Content\Types\CategorySelection(($this->services['sulu_category.category_manager'] ?? $this->getSuluCategory_CategoryManagerService()));
