<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_website.resolver.parameter' shared service.

return $this->services['sulu_website.resolver.parameter'] = new \Sulu\Bundle\WebsiteBundle\Resolver\ParameterResolver(($this->services['sulu_website.resolver.structure'] ?? $this->getSuluWebsite_Resolver_StructureService()), ($this->privates['sulu_website.resolver.request_analyzer'] ?? $this->load('getSuluWebsite_Resolver_RequestAnalyzerService.php')));
