<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.command.user_password_encoder' shared service.

$this->privates['security.command.user_password_encoder'] = $instance = new \Symfony\Bundle\SecurityBundle\Command\UserPasswordEncoderCommand(($this->services['sulu_security.encoder_factory'] ?? $this->load('getSuluSecurity_EncoderFactoryService.php')), [0 => 'Sulu\\Bundle\\SecurityBundle\\Entity\\User']);

$instance->setName('security:encode-password');

return $instance;
