<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu.repository.role_setting' shared service.

if ($lazyLoad) {
    return $this->services['sulu.repository.role_setting'] = $this->createProxy('RoleSettingRepository_a294c9e', function () {
        return \RoleSettingRepository_a294c9e::staticProxyConstructor(function (&$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface $proxy) {
            $wrappedInstance = $this->load('getSulu_Repository_RoleSettingService.php', false);

            $proxy->setProxyInitializer(null);

            return true;
        });
    });
}

$a = ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService());

return new \Sulu\Bundle\SecurityBundle\Entity\RoleSettingRepository($a, $a->getClassMetadata('Sulu\\Bundle\\SecurityBundle\\Entity\\RoleSetting'));
