<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_document_manager.command.initialize' shared service.

$this->privates['sulu_document_manager.command.initialize'] = $instance = new \Sulu\Bundle\DocumentManagerBundle\Command\InitializeCommand(($this->services['sulu_document_manager.initializer'] ?? $this->load('getSuluDocumentManager_InitializerService.php')));

$instance->setName('sulu:document:initialize');

return $instance;
