<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_document_manager.initializer.workspace' shared service.

return $this->services['sulu_document_manager.initializer.workspace'] = new \Sulu\Bundle\DocumentManagerBundle\Initializer\WorkspaceInitializer(($this->services['doctrine_phpcr'] ?? $this->getDoctrinePhpcrService()));
