<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_page.preview.defaults_provider' shared service.

return $this->privates['sulu_page.preview.defaults_provider'] = new \Sulu\Bundle\PageBundle\Preview\PageRouteDefaultsProvider(($this->services['sulu_page.structure.factory'] ?? $this->getSuluPage_Structure_FactoryService()), ($this->services['sulu_document_manager.document_inspector'] ?? $this->getSuluDocumentManager_DocumentInspectorService()), ($this->services['sulu.content.structure_manager'] ?? $this->getSulu_Content_StructureManagerService()));
