<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_website.routing.portal_loader' shared service.

return $this->privates['sulu_website.routing.portal_loader'] = new \Sulu\Bundle\WebsiteBundle\Routing\PortalLoader();
