<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_website.analytics.event_subscriber' shared service.

return $this->privates['sulu_website.analytics.event_subscriber'] = new \Sulu\Bundle\WebsiteBundle\EventSubscriber\AnalyticsSerializeEventSubscriber();
