<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_security.access_control_manager' shared service.

$a = ($this->services['sulu_security.mask_converter'] ?? $this->load('getSuluSecurity_MaskConverterService.php'));

$this->privates['sulu_security.access_control_manager'] = $instance = new \Sulu\Component\Security\Authorization\AccessControl\AccessControlManager($a, ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()));

$instance->addAccessControlProvider(new \Sulu\Component\Security\Authorization\AccessControl\PhpcrAccessControlProvider(($this->services['sulu_document_manager.document_manager'] ?? $this->getSuluDocumentManager_DocumentManagerService()), $this->parameters['permissions']));
$instance->addAccessControlProvider(new \Sulu\Component\Security\Authorization\AccessControl\DoctrineAccessControlProvider(($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->services['sulu.repository.role'] ?? $this->load('getSulu_Repository_RoleService.php')), ($this->services['sulu.repository.access_control'] ?? $this->load('getSulu_Repository_AccessControlService.php')), $a));

return $instance;
