<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_document_manager.path_builder' shared service.

return $this->privates['sulu_document_manager.path_builder'] = new \Sulu\Component\DocumentManager\PathBuilder(($this->privates['sulu_document_manager.path_segment_registry'] ?? $this->getSuluDocumentManager_PathSegmentRegistryService()));
