<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_page.smart_content.content_type' shared service.

return $this->services['sulu_page.smart_content.content_type'] = new \Sulu\Component\SmartContent\ContentType(($this->services['sulu_page.smart_content.data_provider_pool'] ?? $this->load('getSuluPage_SmartContent_DataProviderPoolService.php')), ($this->services['sulu_tag.tag_manager'] ?? $this->getSuluTag_TagManagerService()), ($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($this->privates['sulu_tag.tag_request_handler'] ?? $this->getSuluTag_TagRequestHandlerService()), ($this->privates['sulu_category.category_request_handler'] ?? $this->getSuluCategory_CategoryRequestHandlerService()), ($this->privates['sulu_tag.reference_store.tag'] ?? ($this->privates['sulu_tag.reference_store.tag'] = new \Sulu\Bundle\WebsiteBundle\ReferenceStore\ReferenceStore())), ($this->privates['sulu_category.reference_store.category'] ?? ($this->privates['sulu_category.reference_store.category'] = new \Sulu\Bundle\WebsiteBundle\ReferenceStore\ReferenceStore())), ($this->services['sulu_audience_targeting.target_group_store'] ?? ($this->services['sulu_audience_targeting.target_group_store'] = new \Sulu\Bundle\AudienceTargetingBundle\TargetGroup\TargetGroupStore())));
