<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_security.permission_controller' shared service.

return $this->services['sulu_security.permission_controller'] = new \Sulu\Bundle\SecurityBundle\Controller\PermissionController(($this->privates['sulu_security.access_control_manager'] ?? $this->load('getSuluSecurity_AccessControlManagerService.php')), ($this->services['sulu_security.security_checker'] ?? $this->getSuluSecurity_SecurityCheckerService()), ($this->services['sulu.repository.role'] ?? $this->load('getSulu_Repository_RoleService.php')), ($this->services['fos_rest.view_handler'] ?? $this->load('getFosRest_ViewHandlerService.php')), $this->parameters['sulu_admin.resources']);
