<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_security.user_manager' shared service.

return $this->services['sulu_security.user_manager'] = new \Sulu\Bundle\SecurityBundle\UserManager\UserManager(($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->services['sulu_security.encoder_factory'] ?? $this->load('getSuluSecurity_EncoderFactoryService.php')), ($this->services['sulu.repository.role'] ?? $this->load('getSulu_Repository_RoleService.php')), ($this->privates['sulu_security.group_repository'] ?? $this->load('getSuluSecurity_GroupRepositoryService.php')), ($this->services['sulu_contact.contact_manager'] ?? $this->load('getSuluContact_ContactManagerService.php')), ($this->services['sulu_security.salt_generator'] ?? ($this->services['sulu_security.salt_generator'] = new \Sulu\Component\Security\Authentication\SaltGenerator())), ($this->services['sulu.repository.user'] ?? $this->getSulu_Repository_UserService()));
