<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_contact.smart_content.data_provider.contact' shared service.

return $this->privates['sulu_contact.smart_content.data_provider.contact'] = new \Sulu\Component\Contact\SmartContent\ContactDataProvider(($this->services['sulu_contact.contact_manager'] ?? $this->load('getSuluContact_ContactManagerService.php')), ($this->services['jms_serializer'] ?? $this->getJmsSerializerService()), ($this->privates['sulu_contact.reference_store.contact'] ?? ($this->privates['sulu_contact.reference_store.contact'] = new \Sulu\Bundle\WebsiteBundle\ReferenceStore\ReferenceStore())));
