<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_form.metadata.properties_xml_loader' shared service.

return $this->privates['sulu_form.metadata.properties_xml_loader'] = new \Sulu\Bundle\FormBundle\Metadata\PropertiesXmlLoader(($this->privates['sulu_page.structure.properties_xml_parser'] ?? $this->getSuluPage_Structure_PropertiesXmlParserService()));
