<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_core.rest.view_handler.csv' shared service.

return $this->privates['sulu_core.rest.view_handler.csv'] = new \Sulu\Component\Rest\Csv\CsvHandler(($this->services['jms_serializer'] ?? $this->getJmsSerializerService()));
