<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_core.list_builder.metadata.provider.list' shared service.

return $this->privates['sulu_core.list_builder.metadata.provider.list'] = new \Sulu\Component\Rest\ListBuilder\Metadata\ListXmlLoader(($this->privates['sulu_core.list_builder.metadata.parameter_bag'] ?? $this->load('getSuluCore_ListBuilder_Metadata_ParameterBagService.php')));
