<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_page.webspace.serializer.event_subscriber' shared service.

return $this->privates['sulu_page.webspace.serializer.event_subscriber'] = new \Sulu\Bundle\PageBundle\EventListener\WebspaceSerializeEventSubscriber(($this->services['sulu_core.webspace.webspace_manager'] ?? $this->getSuluCore_Webspace_WebspaceManagerService()), ($this->privates['sulu_core.webspace.url_provider'] ?? $this->load('getSuluCore_Webspace_UrlProviderService.php')), 'test');
