<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_audience_targeting.serializer.target_group_rule_serializer' shared service.

return $this->privates['sulu_audience_targeting.serializer.target_group_rule_serializer'] = new \Sulu\Bundle\AudienceTargetingBundle\Serializer\Subscriber\TargetGroupRuleSerializeSubscriber();
