<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_website.resolver.template_attribute' shared service.

return $this->services['sulu_website.resolver.template_attribute'] = new \Sulu\Bundle\WebsiteBundle\Resolver\TemplateAttributeResolver(($this->services['sulu_core.webspace.request_analyzer'] ?? $this->getSuluCore_Webspace_RequestAnalyzerService()), ($this->privates['sulu_website.resolver.request_analyzer'] ?? $this->load('getSuluWebsite_Resolver_RequestAnalyzerService.php')), ($this->services['sulu_core.webspace.webspace_manager'] ?? $this->getSuluCore_Webspace_WebspaceManagerService()), ($this->services['router'] ?? $this->getRouterService()), ($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), 'test');
