<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_document_manager.document.subscriber.publish' shared service.

return $this->privates['sulu_document_manager.document.subscriber.publish'] = new \Sulu\Bundle\PageBundle\Document\Subscriber\PublishSubscriber(($this->services['sulu_test.doctrine_phpcr.live_session'] ?? $this->getSuluTest_DoctrinePhpcr_LiveSessionService()), ($this->privates['sulu_document_manager.node_helper'] ?? ($this->privates['sulu_document_manager.node_helper'] = new \Sulu\Component\DocumentManager\NodeHelper())), ($this->services['sulu_document_manager.property_encoder'] ?? $this->getSuluDocumentManager_PropertyEncoderService()), ($this->privates['sulu_document_manager.metadata_factory'] ?? $this->getSuluDocumentManager_MetadataFactoryService()));
