<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_audience_targeting.rules_collection' shared service.

return $this->privates['sulu_audience_targeting.rules_collection'] = new \Sulu\Bundle\AudienceTargetingBundle\Rule\RuleCollection(['page' => ($this->privates['sulu_audience_targeting.rules.page'] ?? $this->load('getSuluAudienceTargeting_Rules_PageService.php')), 'locale' => ($this->privates['sulu_audience_targeting.rules.locale'] ?? $this->load('getSuluAudienceTargeting_Rules_LocaleService.php')), 'referrer' => ($this->privates['sulu_audience_targeting.rules.referrer'] ?? $this->load('getSuluAudienceTargeting_Rules_ReferrerService.php')), 'query_string' => ($this->privates['sulu_audience_targeting.rules.query_string'] ?? $this->load('getSuluAudienceTargeting_Rules_QueryStringService.php')), 'browser' => ($this->privates['sulu_audience_targeting.rules.browser'] ?? $this->load('getSuluAudienceTargeting_Rules_BrowserService.php')), 'os' => ($this->privates['sulu_audience_targeting.rules.os'] ?? $this->load('getSuluAudienceTargeting_Rules_OsService.php')), 'device' => ($this->privates['sulu_audience_targeting.rules.device'] ?? $this->load('getSuluAudienceTargeting_Rules_DeviceService.php'))]);
