<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_page.smart_content.data_provider.content.proxy_factory' shared service.

return $this->privates['sulu_page.smart_content.data_provider.content.proxy_factory'] = new \ProxyManager\Factory\LazyLoadingValueHolderFactory(($this->privates['sulu_core.proxy_manager.configuration'] ?? $this->getSuluCore_ProxyManager_ConfigurationService()));
