<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_snippet.form.snippet' shared service.

return $this->privates['sulu_snippet.form.snippet'] = new \Sulu\Bundle\SnippetBundle\Form\SnippetType();
