<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu.repository.target_group_webspace' shared service.

if ($lazyLoad) {
    return $this->services['sulu.repository.target_group_webspace'] = $this->createProxy('TargetGroupWebspaceRepository_a4f1c1d', function () {
        return \TargetGroupWebspaceRepository_a4f1c1d::staticProxyConstructor(function (&$wrappedInstance, \ProxyManager\Proxy\LazyLoadingInterface $proxy) {
            $wrappedInstance = $this->load('getSulu_Repository_TargetGroupWebspaceService.php', false);

            $proxy->setProxyInitializer(null);

            return true;
        });
    });
}

$a = ($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService());

return new \Sulu\Bundle\AudienceTargetingBundle\Entity\TargetGroupWebspaceRepository($a, $a->getClassMetadata('Sulu\\Bundle\\AudienceTargetingBundle\\Entity\\TargetGroupWebspace'));
