<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_core.doctrine_rest_helper' shared service.

return $this->services['sulu_core.doctrine_rest_helper'] = new \Sulu\Component\Rest\DoctrineRestHelper(($this->services['sulu_core.list_rest_helper'] ?? $this->load('getSuluCore_ListRestHelperService.php')));
