<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_preview.preview' shared service.

return $this->privates['sulu_preview.preview'] = new \Sulu\Bundle\PreviewBundle\Preview\Preview(['pages' => ($this->privates['sulu_page.preview.object_provider'] ?? $this->load('getSuluPage_Preview_ObjectProviderService.php'))], ($this->services['doctrine_cache.providers.sulu_preview'] ?? ($this->services['doctrine_cache.providers.sulu_preview'] = new \Doctrine\Common\Cache\FilesystemCache(($this->targetDirs[0].'/sulu/preview'), NULL, 2))), ($this->privates['sulu_preview.preview.renderer'] ?? $this->load('getSuluPreview_Preview_RendererService.php')));
