<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_contact.content.single_account_selection' shared service.

return $this->services['sulu_contact.content.single_account_selection'] = new \Sulu\Bundle\ContactBundle\Content\Types\SingleAccountSelection(($this->services['sulu_contact.account_manager'] ?? $this->load('getSuluContact_AccountManagerService.php')), ($this->privates['sulu_contact.reference_store.account'] ?? ($this->privates['sulu_contact.reference_store.account'] = new \Sulu\Bundle\WebsiteBundle\ReferenceStore\ReferenceStore())));
