<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_page.smart_content.data_provider.content' shared service.

return $this->privates['sulu_page.smart_content.data_provider.content'] = new \Sulu\Component\Content\SmartContent\PageDataProvider(($this->privates['sulu_page.smart_content.data_provider.content.query_builder'] ?? $this->load('getSuluPage_SmartContent_DataProvider_Content_QueryBuilderService.php')), ($this->privates['sulu.content.query_executor'] ?? $this->getSulu_Content_QueryExecutorService()), ($this->services['sulu_document_manager.document_manager'] ?? $this->getSuluDocumentManager_DocumentManagerService()), ($this->privates['sulu_page.smart_content.data_provider.content.proxy_factory'] ?? $this->load('getSuluPage_SmartContent_DataProvider_Content_ProxyFactoryService.php')), ($this->services['sulu_test.doctrine_phpcr.default_session'] ?? $this->getSuluTest_DoctrinePhpcr_DefaultSessionService()), ($this->privates['sulu_page.reference_store.content'] ?? ($this->privates['sulu_page.reference_store.content'] = new \Sulu\Bundle\WebsiteBundle\ReferenceStore\ReferenceStore())), true);
