<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_snippet.import.webspace.xliff12' shared service.

return $this->privates['sulu_snippet.import.webspace.xliff12'] = new \Sulu\Component\Import\Format\Xliff12();
