<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu.content.type.resource_locator' shared service.

return $this->services['sulu.content.type.resource_locator'] = new \Sulu\Component\Content\Types\ResourceLocator();
