<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_snippet.import.snippet' shared service.

return $this->services['sulu_snippet.import.snippet'] = new \Sulu\Component\Snippet\Import\SnippetImport(($this->services['sulu_document_manager.document_manager'] ?? $this->getSuluDocumentManager_DocumentManagerService()), ($this->services['sulu.content.structure_manager'] ?? $this->getSulu_Content_StructureManagerService()), ($this->privates['sulu_document_manager.document_registry'] ?? ($this->privates['sulu_document_manager.document_registry'] = new \Sulu\Component\DocumentManager\DocumentRegistry('en'))), ($this->privates['sulu_page.import.manager'] ?? $this->getSuluPage_Import_ManagerService()), ($this->services['sulu_page.compat.structure.legacy_property_factory'] ?? $this->getSuluPage_Compat_Structure_LegacyPropertyFactoryService()), ($this->privates['sulu_snippet.import.webspace.xliff12'] ?? ($this->privates['sulu_snippet.import.webspace.xliff12'] = new \Sulu\Component\Import\Format\Xliff12())), ($this->privates['monolog.logger'] ?? $this->getMonolog_LoggerService()));
