<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_route.manager.route_manager' shared service.

return $this->privates['sulu_route.manager.route_manager'] = new \Sulu\Bundle\RouteBundle\Manager\RouteManager(($this->privates['sulu_route.chain_generator'] ?? $this->load('getSuluRoute_ChainGeneratorService.php')), ($this->privates['sulu_route.manager.conflict_resolver.auto_increment'] ?? $this->load('getSuluRoute_Manager_ConflictResolver_AutoIncrementService.php')), ($this->services['sulu.repository.route'] ?? $this->load('getSulu_Repository_RouteService.php')));
