<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_document_manager.data_fixtures.executor' shared service.

return $this->privates['sulu_document_manager.data_fixtures.executor'] = new \Sulu\Bundle\DocumentManagerBundle\DataFixtures\DocumentExecutor(($this->services['sulu_document_manager.document_manager'] ?? $this->getSuluDocumentManager_DocumentManagerService()), ($this->services['sulu_document_manager.initializer'] ?? $this->load('getSuluDocumentManager_InitializerService.php')));
