<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_page.document.serializer.handler.structure' shared service.

return $this->privates['sulu_page.document.serializer.handler.structure'] = new \Sulu\Bundle\PageBundle\Serializer\Handler\StructureHandler();
