<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_snippet.controller.snippet' shared service.

return $this->services['sulu_snippet.controller.snippet'] = new \Sulu\Bundle\SnippetBundle\Controller\SnippetController(($this->services['fos_rest.view_handler'] ?? $this->load('getFosRest_ViewHandlerService.php')), ($this->services['sulu.content.mapper'] ?? $this->getSulu_Content_MapperService()), ($this->services['sulu.content.structure_manager'] ?? $this->getSulu_Content_StructureManagerService()), ($this->services['sulu_snippet.repository'] ?? $this->load('getSuluSnippet_RepositoryService.php')), ($this->services['security.token_storage'] ?? ($this->services['security.token_storage'] = new \Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage())), ($this->services['router'] ?? $this->getRouterService()), ($this->services['sulu_snippet.default_snippet.manager'] ?? $this->getSuluSnippet_DefaultSnippet_ManagerService()), ($this->services['sulu_document_manager.document_manager'] ?? $this->getSuluDocumentManager_DocumentManagerService()), ($this->services['form.factory'] ?? $this->getForm_FactoryService()), ($this->services['sulu_hash.request_hash_checker'] ?? $this->load('getSuluHash_RequestHashCheckerService.php')), ($this->services['sulu_core.list_rest_helper'] ?? $this->load('getSuluCore_ListRestHelperService.php')), ($this->services['sulu_document_manager.metadata_factory.base'] ?? $this->getSuluDocumentManager_MetadataFactory_BaseService()));
