<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_media.type.media_selection' shared service.

return $this->services['sulu_media.type.media_selection'] = new \Sulu\Bundle\MediaBundle\Content\Types\MediaSelectionContentType(($this->services['sulu_media.media_manager'] ?? $this->getSuluMedia_MediaManagerService()), ($this->privates['sulu_media.reference_store.media'] ?? ($this->privates['sulu_media.reference_store.media'] = new \Sulu\Bundle\WebsiteBundle\ReferenceStore\ReferenceStore())));
