<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_document_manager.suscriber.behavior.author' shared service.

return $this->privates['sulu_document_manager.suscriber.behavior.author'] = new \Sulu\Component\Content\Document\Subscriber\AuthorSubscriber(($this->services['sulu_document_manager.property_encoder'] ?? $this->getSuluDocumentManager_PropertyEncoderService()), ($this->services['sulu.repository.user'] ?? $this->getSulu_Repository_UserService()), ($this->privates['sulu_document_manager.metadata_factory'] ?? $this->getSuluDocumentManager_MetadataFactoryService()));
