<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_admin.navigation_registry' shared service.

return $this->privates['sulu_admin.navigation_registry'] = new \Sulu\Bundle\AdminBundle\Admin\Navigation\NavigationRegistry(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['sulu_admin.admin_pool'] ?? $this->load('getSuluAdmin_AdminPoolService.php')), ($this->privates['sulu_admin.route_registry'] ?? $this->load('getSuluAdmin_RouteRegistryService.php')));
