<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_document_manager.initializer' shared service.

return $this->services['sulu_document_manager.initializer'] = new \Sulu\Bundle\DocumentManagerBundle\Initializer\Initializer($this, ['sulu_core.webspace.document_manager.webspace_initializer' => 0, 'sulu_page.document_manager.content_initializer' => 127, 'sulu_snippet.document.snippet_initializer' => 0, 'sulu_document_manager.initializer.root_path_purge_initializer' => 250, 'sulu_document_manager.initializer.workspace' => 255, 'sulu_custom_urls.initializer' => -127]);
