<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_hash.auditable_hasher' shared service.

return $this->privates['sulu_hash.auditable_hasher'] = new \Sulu\Component\Hash\AuditableHasher();
