<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_custom_urls.event_subscriber.invalidation' shared service.

return $this->privates['sulu_custom_urls.event_subscriber.invalidation'] = new \Sulu\Component\CustomUrl\Document\Subscriber\InvalidationSubscriber(($this->services['sulu_custom_urls.manager'] ?? $this->load('getSuluCustomUrls_ManagerService.php')), ($this->services['sulu_document_manager.document_inspector'] ?? $this->getSuluDocumentManager_DocumentInspectorService()), NULL, ($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
