<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_audience_targeting.webspace_select_helper' shared service.

return $this->services['sulu_audience_targeting.webspace_select_helper'] = new \Sulu\Bundle\AudienceTargetingBundle\Admin\Helper\WebspaceSelect(($this->services['sulu_core.webspace.webspace_manager'] ?? $this->getSuluCore_Webspace_WebspaceManagerService()));
