<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_page.teaser.content_type' shared service.

return $this->services['sulu_page.teaser.content_type'] = new \Sulu\Bundle\PageBundle\Teaser\TeaserContentType(($this->privates['sulu_page.teaser.provider_pool'] ?? $this->load('getSuluPage_Teaser_ProviderPoolService.php')), ($this->privates['sulu_page.teaser.manager'] ?? $this->load('getSuluPage_Teaser_ManagerService.php')), ($this->privates['sulu_website.reference_store_pool'] ?? $this->load('getSuluWebsite_ReferenceStorePoolService.php')));
