<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_form.list_builder.dynamic_list_builder' shared service.

return $this->privates['sulu_form.list_builder.dynamic_list_builder'] = new \Sulu\Bundle\FormBundle\ListBuilder\DynamicListBuilder(''."\n".'', ($this->services['router'] ?? $this->getRouterService()));
