<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_form_test.dynamic_list_metadata_loader' shared service.

return $this->services['sulu_form_test.dynamic_list_metadata_loader'] = new \Sulu\Bundle\FormBundle\Metadata\DynamicListMetadataLoader(($this->services['translator'] ?? $this->getTranslatorService()), ($this->services['sulu_form.manager.form'] ?? $this->load('getSuluForm_Manager_FormService.php')), ($this->privates['sulu_form.list_builder.dynamic_list_factory'] ?? $this->load('getSuluForm_ListBuilder_DynamicListFactoryService.php')));
