<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_page.teaser.manager' shared service.

return $this->privates['sulu_page.teaser.manager'] = new \Sulu\Bundle\PageBundle\Teaser\TeaserManager(($this->privates['sulu_page.teaser.provider_pool'] ?? $this->load('getSuluPage_Teaser_ProviderPoolService.php')));
