<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_page.document.serializer.subscriber.parent_behavior' shared service.

return $this->privates['sulu_page.document.serializer.subscriber.parent_behavior'] = new \Sulu\Bundle\PageBundle\Serializer\Subscriber\ParentSubscriber();
