<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_audience_targeting.rules.locale' shared service.

return $this->privates['sulu_audience_targeting.rules.locale'] = new \Sulu\Bundle\AudienceTargetingBundle\Rule\LocaleRule(($this->services['request_stack'] ?? ($this->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())), ($this->services['translator'] ?? $this->getTranslatorService()));
