<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_website.sitemap.pool' shared service.

return $this->services['sulu_website.sitemap.pool'] = new \Sulu\Bundle\WebsiteBundle\Sitemap\SitemapProviderPool(['pages' => ($this->privates['sulu_website.sitemap.pages_provider'] ?? $this->load('getSuluWebsite_Sitemap_PagesProviderService.php'))]);
