<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_media.format_options_manager' shared service.

return $this->services['sulu_media.format_options_manager'] = new \Sulu\Bundle\MediaBundle\Media\FormatOptions\FormatOptionsManager(($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->privates['sulu_media.format_options_repository'] ?? $this->load('getSuluMedia_FormatOptionsRepositoryService.php')), ($this->services['sulu_media.media_manager'] ?? $this->getSuluMedia_MediaManagerService()), ($this->services['sulu_media.format_manager'] ?? $this->getSuluMedia_FormatManagerService()), $this->parameters['sulu_media.image.formats']);
