<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_contact.content.single_contact_selection' shared service.

return $this->services['sulu_contact.content.single_contact_selection'] = new \Sulu\Bundle\ContactBundle\Content\Types\SingleContactSelection(($this->services['sulu.repository.contact'] ?? $this->getSulu_Repository_ContactService()), ($this->privates['sulu_contact.reference_store.contact'] ?? ($this->privates['sulu_contact.reference_store.contact'] = new \Sulu\Bundle\WebsiteBundle\ReferenceStore\ReferenceStore())));
