<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_website.event_listener.translator' shared service.

return $this->privates['sulu_website.event_listener.translator'] = new \Sulu\Bundle\WebsiteBundle\EventListener\TranslatorEventListener(($this->services['translator'] ?? $this->getTranslatorService()));
