<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_page.smart_content.data_provider_pool' shared service.

$this->services['sulu_page.smart_content.data_provider_pool'] = $instance = new \Sulu\Component\SmartContent\DataProviderPool($this->hasParameter("sulu_audience_targeting.enabled"));

$instance->add('pages', ($this->privates['sulu_page.smart_content.data_provider.content'] ?? $this->load('getSuluPage_SmartContent_DataProvider_ContentService.php')));
$instance->add('contacts', ($this->privates['sulu_contact.smart_content.data_provider.contact'] ?? $this->load('getSuluContact_SmartContent_DataProvider_ContactService.php')));
$instance->add('accounts', ($this->privates['sulu_contact.smart_content.data_provider.account'] ?? $this->load('getSuluContact_SmartContent_DataProvider_AccountService.php')));
$instance->add('media', ($this->privates['sulu_media.smart_content.data_provider.media'] ?? $this->load('getSuluMedia_SmartContent_DataProvider_MediaService.php')));
$instance->add('snippets', ($this->privates['sulu_snippet.smart_content.snippet_data_provider'] ?? $this->load('getSuluSnippet_SmartContent_SnippetDataProviderService.php')));

return $instance;
