<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_page.export.webspace' shared service.

return $this->services['sulu_page.export.webspace'] = new \Sulu\Component\Content\Export\WebspaceExport(($this->services['templating'] ?? $this->load('getTemplatingService.php')), ($this->services['sulu_document_manager.document_manager'] ?? $this->getSuluDocumentManager_DocumentManagerService()), ($this->services['sulu_document_manager.document_inspector'] ?? $this->getSuluDocumentManager_DocumentInspectorService()), ($this->services['sulu.content.structure_manager'] ?? $this->getSulu_Content_StructureManagerService()), ($this->services['sulu_page.extension.manager'] ?? $this->getSuluPage_Extension_ManagerService()), ($this->privates['sulu_page.export.manager'] ?? $this->getSuluPage_Export_ManagerService()), $this->parameters['sulu_page.export.webspace.formats']);
