<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_media.smart_content.data_provider.media.repository' shared service.

return $this->privates['sulu_media.smart_content.data_provider.media.repository'] = new \Sulu\Bundle\MediaBundle\Entity\MediaDataProviderRepository(($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->services['sulu_media.media_manager'] ?? $this->getSuluMedia_MediaManagerService()), 'Sulu\\Bundle\\MediaBundle\\Entity\\Media', 'SuluMediaBundle:Collection');
