<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_search.controller.search' shared service.

return $this->services['sulu_search.controller.search'] = new \Sulu\Bundle\SearchBundle\Controller\SearchController(($this->services['massive_search.search_manager'] ?? $this->load('getMassiveSearch_SearchManagerService.php')), ($this->privates['massive_search.metadata.provider.chain'] ?? $this->load('getMassiveSearch_Metadata_Provider_ChainService.php')), ($this->services['sulu_security.security_checker'] ?? $this->getSuluSecurity_SecurityCheckerService()), ($this->services['fos_rest.view_handler'] ?? $this->load('getFosRest_ViewHandlerService.php')), ($this->services['sulu_core.list_rest_helper'] ?? $this->load('getSuluCore_ListRestHelperService.php')), ($this->privates['sulu_search.index_configuration_provider'] ?? $this->load('getSuluSearch_IndexConfigurationProviderService.php')));
