<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_document_manager.subscriber.behavior.path' shared service.

return $this->privates['sulu_document_manager.subscriber.behavior.path'] = new \Sulu\Component\DocumentManager\Subscriber\Behavior\Mapping\PathSubscriber(($this->services['sulu_document_manager.document_inspector'] ?? $this->getSuluDocumentManager_DocumentInspectorService()));
