<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_document_manager.subscriber.core.instantiator' shared service.

return $this->privates['sulu_document_manager.subscriber.core.instantiator'] = new \Sulu\Component\DocumentManager\Subscriber\Core\InstantiatorSubscriber(($this->privates['sulu_document_manager.metadata_factory'] ?? $this->getSuluDocumentManager_MetadataFactoryService()));
