<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_audience_targeting.target_group_evaluation_controller' shared service.

return $this->services['sulu_audience_targeting.target_group_evaluation_controller'] = new \Sulu\Bundle\AudienceTargetingBundle\Controller\TargetGroupEvaluationController(($this->privates['sulu_audience_targeting.target_group_evaluator'] ?? $this->load('getSuluAudienceTargeting_TargetGroupEvaluatorService.php')), ($this->services['sulu.repository.target_group'] ?? $this->getSulu_Repository_TargetGroupService()), ($this->services['sulu_audience_targeting.target_group_store'] ?? ($this->services['sulu_audience_targeting.target_group_store'] = new \Sulu\Bundle\AudienceTargetingBundle\TargetGroup\TargetGroupStore())), 'X-Sulu-Target-Group');
