<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_website.command.dump_sitemap' shared service.

$this->privates['sulu_website.command.dump_sitemap'] = $instance = new \Sulu\Bundle\WebsiteBundle\Command\DumpSitemapCommand(($this->services['sulu_core.webspace.webspace_manager'] ?? $this->getSuluCore_Webspace_WebspaceManagerService()), ($this->services['sulu_website.sitemap.xml_dumper'] ?? $this->load('getSuluWebsite_Sitemap_XmlDumperService.php')), ($this->services['filesystem'] ?? ($this->services['filesystem'] = new \Symfony\Component\Filesystem\Filesystem())), 'test', ($this->targetDirs[0].'/sulu/sitemaps'));

$instance->setName('sulu:website:dump-sitemap');

return $instance;
