<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_audience_targeting.target_group_store' shared service.

return $this->services['sulu_audience_targeting.target_group_store'] = new \Sulu\Bundle\AudienceTargetingBundle\TargetGroup\TargetGroupStore();
