<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_media.command.format_cache.cleanup' shared service.

$this->privates['sulu_media.command.format_cache.cleanup'] = $instance = new \Sulu\Bundle\MediaBundle\Command\FormatCacheCleanupCommand(($this->services['sulu.repository.media'] ?? $this->getSulu_Repository_MediaService()), ($this->services['filesystem'] ?? ($this->services['filesystem'] = new \Symfony\Component\Filesystem\Filesystem())), ($this->targetDirs[4].'/public/uploads/media'));

$instance->setName('sulu:media:format:cache:cleanup');

return $instance;
