<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'sulu_core.webspace.url_provider' shared service.

return $this->privates['sulu_core.webspace.url_provider'] = new \Sulu\Component\Webspace\Url\WebspaceUrlChainProvider([0 => ($this->privates['sulu_core.webspace.url_provider.default'] ?? ($this->privates['sulu_core.webspace.url_provider.default'] = new \Sulu\Component\Webspace\Url\WebspaceUrlProvider())), 1 => ($this->privates['sulu_custom_urls.url_provider'] ?? $this->load('getSuluCustomUrls_UrlProviderService.php'))]);
