<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'sulu_hash.request_hash_checker' shared service.

return $this->services['sulu_hash.request_hash_checker'] = new \Sulu\Component\Hash\RequestHashChecker(($this->privates['sulu_hash.auditable_hasher'] ?? ($this->privates['sulu_hash.auditable_hasher'] = new \Sulu\Component\Hash\AuditableHasher())));
