<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'twig.template_iterator' shared service.

return $this->privates['twig.template_iterator'] = new \Symfony\Bundle\TwigBundle\TemplateIterator(($this->services['kernel'] ?? $this->get('kernel', 1)), $this->targetDirs[4], ['/Users/danielmathis/Development/sulu-website/sulu-docker/project/vendor/sulu/sulu-form-bundle/vendor/symfony/twig-bridge/Resources/views/Form' => NULL], ($this->targetDirs[4].'/templates'));
