<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'test_user_provider' shared service.

return $this->services['test_user_provider'] = new \Sulu\Bundle\TestBundle\Testing\TestUserProvider(($this->services['doctrine.orm.default_entity_manager'] ?? $this->getDoctrine_Orm_DefaultEntityManagerService()), ($this->services['sulu.repository.contact'] ?? $this->getSulu_Repository_ContactService()), ($this->services['sulu.repository.user'] ?? $this->getSulu_Repository_UserService()));
