<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'console.command.public_alias.Doctrine\Bundle\PHPCRBundle\Command\WorkspaceCreateCommand' shared service.

return $this->services['console.command.public_alias.Doctrine\\Bundle\\PHPCRBundle\\Command\\WorkspaceCreateCommand'] = new \Doctrine\Bundle\PHPCRBundle\Command\WorkspaceCreateCommand();
