<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIN5dxNM\adminAdminTestDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIN5dxNM/adminAdminTestDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerIN5dxNM.legacy');

    return;
}

if (!\class_exists(adminAdminTestDebugProjectContainer::class, false)) {
    \class_alias(\ContainerIN5dxNM\adminAdminTestDebugProjectContainer::class, adminAdminTestDebugProjectContainer::class, false);
}

return new \ContainerIN5dxNM\adminAdminTestDebugProjectContainer([
    'container.build_hash' => 'IN5dxNM',
    'container.build_id' => '9be0245b',
    'container.build_time' => 1568623933,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIN5dxNM');
